**Nama anggota :**\
**1. Ammalya Khoirun Nizak (25031554036) (mengerjakan bagian HTTP Scraping)**\
**2. Muhammad Rifky Ihwan (250315540241) (mengerjakan bagian API)**

**Scraping with HTTP**

In [ ]:
import requests

In [ ]:
page = requests.get('https://www.historia.id/articles/categories/politik')
page

In [ ]:
print(page.text)

<!DOCTYPE html>
<html lang="id">
<head>

  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1" id="wixDesktopViewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Wix.com Website Builder"/>

  <link rel="icon" sizes="192x192" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>
  <link rel="shortcut icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>
  <link rel="apple-touch-icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_180%2Ch_180%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>

  <!-- Safari Pinned Tab Icon -->
  <!-- <link rel="mask-icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png"> -->

  <!-- Segmenter Polyfill -->
  <script>
    if (!window.Intl || !window.Intl.Segmenter) {
      (function() {
        var script = document.createElement('script');
        script.src = 'https://static.parastorage.com/unpkg/@formatjs/intl-segmenter@11.7.10/polyfill.iife.js';
        document.head.appendChild(script);
      })();
    }
  </script>

  <!-- Legacy Polyfills -->
  <script nomodule="" src="https://static.parastorage.com/unpkg/core-js-bundle@3.2.1/minified.js"></script>
  <script nomodule="" src="https://static.parastorage.com/unpkg/focus-within-polyfill@5.0.9/dist/focus-within-polyfill.js"></script>

  <!-- Performance API Polyfills -->
  <script>
  (function () {
    var noop = function noop() {};
    if ("performance" in window === false) {
      window.performance = {};
    }
    window.performance.mark = performance.mark || noop;
    window.performance.measure = performance.measure || noop;
    if ("now" in window.performance === false) {
      var nowOffset = Date.now();
      if (performance.timing && performance.timing.navigationStart) {
        nowOffset = performance.timing.navigationStart;
      }
      window.performance.now = function now() {
        return Date.now() - nowOffset;
      };
    }
  })();
  </script>


    <!-- Essential Viewer Model -->
    <script type="application/json" id="wix-essential-viewer-model">{"fleetConfig":{"fleetName":"thunderbolt-isolated-renderer","type":"GA","code":0},"mode":{"qa":false,"enableTestApi":false,"addAllServices":false,"debug":false,"ssrIndicator":false,"ssrOnly":false,"siteAssetsFallback":"enable","versionIndicator":false},"componentsLibrariesTopology":[{"artifactId":"editor-elements","namespace":"wixui","url":"https:\/\/static.parastorage.com\/services\/editor-elements\/1.15516.0"},{"artifactId":"editor-elements","namespace":"dsgnsys","url":"https:\/\/static.parastorage.com\/services\/editor-elements\/1.15516.0"}],"siteFeaturesConfigs":{"sessionManager":{"isRunningInDifferentSiteContext":false}},"language":{"userLanguage":"id"},"siteAssets":{"clientTopology":{"mediaRootUrl":"https:\/\/static.wixstatic.com","scriptsUrl":"static.parastorage.com","staticMediaUrl":"https:\/\/static.wixstatic.com\/media","staticAudioUrl":"https:\/\/music.wixstatic.com\/mp3","moduleRepoUrl":"https:\/\/static.parastorage.com\/unpkg","fileRepoUrl":"https:\/\/static.parastorage.com\/services","viewerAppsUrl":"https:\/\/viewer-apps.parastorage.com","viewerAssetsUrl":"https:\/\/viewer-assets.parastorage.com","siteAssetsUrl":"https:\/\/siteassets.parastorage.com","pageJsonServerUrls":["https:\/\/pages.parastorage.com","https:\/\/staticorigin.wixstatic.com","https:\/\/www.historia.id","https:\/\/fallback.wix.com\/wix-html-editor-pages-webapp\/page"],"pathOfTBModulesInFileRepoForFallback":"wix-thunderbolt\/dist\/"}},"siteFeatures":["accessibilityBrowserZoom","appMonitoring","assetsLoader","businessLogger","captcha","clickHandlerRegistrar","clientSdk","codeEmbed","commonConfig","componentsRegistry","consentPolicy","cookiesManager","customCss","customUrlMapper","cyclicTabbing","domSelectors","domStore","dynamicPages","environmentWixCodeSdk","environment","externalServices","lightbox","locationWixCodeSdk","mpaNavigation","multilingual","navigationManager","navigationPhases","ooi","pages","panorama","protectedPages","renderer","reporter","routerFetch","router","scrollRestoration","seoWixCodeSdk","seo","sessionManager","siteMembersWixCodeSdk","siteMembers","siteScrollBlocker","siteWixCodeSdk","speculationRules","ssrCache","stores","structureApi","thunderboltInitializer","tpaCommons","translations","usedPlatformApis","warmupData","windowMessageRegistrar","windowWixCodeSdk","wixCustomElementComponent","wixEmbedsApi","componentsLoader","componentsReact","platform"],"site":{"externalBaseUrl":"https:\/\/www.historia.id","isSEO":false},"media":{"staticMediaUrl":"https:\/\/static.wixstatic.com\/media","mediaRootUrl":"https:\/\/static.wixstatic.com\/","staticVideoUrl":"https:\/\/video.wixstatic.com\/","userDomainMediaPrefixes":[]},"requestUrl":"https:\/\/www.historia.id\/articles\/categories\/politik","rollout":{"siteAssetsVersionsRollout":false,"isDACRollout":0,"isTBRollout":false},"commonConfig":{"brand":"studio","host":"VIEWER","bsi":"","consentPolicy":{},"consentPolicyHeader":{},"siteRevision":"3694","renderingFlow":"NONE","language":"id","locale":"id-id"},"interactionSampleRatio":0.01,"accessTokensUrl":"https:\/\/www.historia.id\/_api\/v1\/access-tokens","experiments":{"specs.thunderbolt.hardenFetchAndXHR":true,"specs.thunderbolt.securityExperiments":true,"specs.thunderbolt.allowWebpAvifTransforms":true,"specs.thunderbolt.browserCacheReload":true,"specs.thunderbolt.browserZoomMobileOnloadDetection":true}}</script>
    <script>window.viewerModel = JSON.parse(document.getElementById('wix-essential-viewer-model').textContent)</script>


  <!-- Globals Definitions -->
  <script>
    (function () {
      var now = Date.now()
      var activationStart = 0
      try {
        var navEntry = performance.getEntriesByType('navigation')[0];
        if (navEntry && navEntry.activationStart > 0) {
          activationStart = navEntry.activationStart;
        }
      } catch (e) {}
      window.initialTimestamps = {
        initialTimestamp: now,
        initialRequestTimestamp: Math.round(performance.timeOrigin ? performance.timeOrigin + activationStart : now - performance.now() + activationStart)
      }

      window.thunderboltTag = "libs-releases-GA-local"
      window.thunderboltVersion = "1.17950.0"
    })();
  </script>

  <script>
    window.commonConfig = viewerModel.commonConfig
  </script>


  <!-- BEGIN handleAccessTokens bundle -->

  <script data-url="https://static.parastorage.com/services/wix-thunderbolt/dist/handleAccessTokens.inline.3250797b.bundle.min.js">(()=>{"use strict";let e,t,r,o;var n={},i={};function l(e){var t=i[e];if(void 0!==t)return t.exports;var r=i[e]={exports:{}};return n[e](r,r.exports,l),r.exports}function a(e){let{context:t,property:r,value:o,enumerable:n=!0}=e,i=e.get,l=e.set;if(!r||void 0===o&&!i&&!l)return Error("property and value are required");let a=t||globalThis,s=a?.[r],u={};if(void 0!==o)u.value=o;else{if(i){let e=c(i);e&&(u.get=e)}if(l){let e=c(l);e&&(u.set=e)}}let p={...u,enumerable:n||!1,configurable:!1};void 0!==o&&(p.writable=!1);try{Object.defineProperty(a,r,p)}catch(e){return e instanceof TypeError?s:e}return s}function c(e,t){return"function"==typeof e?e:e?.async===!0&&"function"==typeof e.func?t?async function(t){return e.func(t)}:async function(){return e.func()}:"function"==typeof e?.func?e.func:void 0}l.rv=()=>"1.6.8",l.ruid="bundler=rspack@1.6.8";try{a({property:"strictDefine",value:a})}catch{}try{a({property:"defineStrictObject",value:function e(t){let{context:r,property:o,propertiesToExclude:n=[],skipPrototype:i=!1,hardenPrototypePropertiesToExclude:l=[]}=t;if(!o)return Error("property is required");let c=(r||globalThis)[o],p={},f=u(r,o);c&&("object"==typeof c||"function"==typeof c)&&Reflect.ownKeys(c).forEach(e=>{if(!n.includes(e)&&!s.includes(e)){let t=u(c,e);if(t&&(t.writable||t.configurable)){let{value:r,get:o,set:n,enumerable:i=!1}=t,l={};void 0!==r?l.value=r:o?l.get=o:n&&(l.set=n);try{let t=a({context:c,property:e,...l,enumerable:i});p[e]=t}catch(r){if(r instanceof TypeError)try{p[e]=t.value||t.get||t.set}catch{}else throw r}}}});let d={originalObject:c,originalProperties:p};if(!i&&c?.prototype!==void 0){let t=e({context:c,property:"prototype",propertiesToExclude:l,skipPrototype:!0});t instanceof Error||(d.originalPrototype=t?.originalObject,d.originalPrototypeProperties=t?.originalProperties)}return a({context:r,property:o,value:c,enumerable:f?.enumerable}),d}})}catch{}try{a({property:"defineStrictMethod",value:function(e,t){let r=(t||globalThis)[e],o=u(t||globalThis,e);return r&&o&&(o.writable||o.configurable)?(Object.freeze(r),a({context:globalThis,property:e,value:r})):r}})}catch{}var s=["toString","toLocaleString","valueOf","constructor","prototype"];function u(e,t){if(!(!e||!t))try{return Reflect.getOwnPropertyDescriptor(e,t)}catch{return}}function p(e){if("string"!=typeof e)return e;try{return decodeURIComponent(e).toLowerCase().trim()}catch{return e.toLowerCase().trim()}}function f(e,t){let r="";if("string"==typeof e)r=e.split("=")[0]?.trim()||"";else{if(!e||"string"!=typeof e.name)return!1;r=e.name}return t.has(p(r)||"")}function d(e,t){return("string"==typeof e?e.split(";").map(e=>e.trim()).filter(e=>e.length>0):e||[]).filter(e=>!f(e,t))}var y=null;function g(){return null===y&&(y=typeof Document>"u"?void 0:Object.getOwnPropertyDescriptor(Document.prototype,"cookie")),y}let b=(e,t)=>{try{let r=t?t.get.call(document):document.cookie;return r.split(";").map(e=>e.trim()).filter(t=>t?.startsWith(e))[0]?.split("=")[1]}catch(e){return""}},h=(e="",t="",r="/")=>`${e}=; ${t?`domain=${t};`:""} max-age=0; path=${r}; expires=Thu, 01 Jan 1970 00:00:01 GMT`;function m(e,t){try{return sessionStorage[e]("reload",t||"")}catch(e){console.error("ATS: Error calling sessionStorage:",e)}}var v=["true","b","c","new","enabled"];let w=[],S=(e,t)=>{let r;return w.includes(t)||!0===(r=e[t])||"string"==typeof r&&v.includes(r.toLowerCase())},T="client-session-bind",k="sec-fetch-unsupported",{experiments:x}=window.viewerModel,{cookie:E}=(e=new Set([T,"client-binding",k,"svSession","smSession","server-session-bind","wixSession2","wixSession3"].map(e=>e.toLowerCase())),a({context:document,property:"cookie",set:{func:t=>{var r,o;let n,i;return r=document,o=void 0,n=g(),i=p(t.split(";")[0]||"")||"",void([...e].every(e=>!i.startsWith(e.toLowerCase()))&&n?.set?n.set.call(r,t):o&&console.warn(o))}},get:{func:()=>(function(e,t){let r=g();if(!r?.get)throw Error("Cookie descriptor or getter not available");return d(r.get.call(e),t).join("; ")})(document,e)},enumerable:!0}),{cookieStore:function(e,t){if(!globalThis?.cookieStore)return;let r=globalThis.cookieStore.get.bind(globalThis.cookieStore),o=globalThis.cookieStore.getAll.bind(globalThis.cookieStore),n=globalThis.cookieStore.set.bind(globalThis.cookieStore),i=globalThis.cookieStore.delete.bind(globalThis.cookieStore);return a({context:globalThis.CookieStore.prototype,property:"get",value:async function(t){return f(("string"==typeof t?t:t.name)||"",e)?null:r.call(this,t)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"getAll",value:async function(){let t=await o.apply(this,Array.from(arguments));return d(t,e)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"set",value:async function(){let r=Array.from(arguments);if(!f(1===r.length?r[0].name:r[0],e))return n.apply(this,r);t&&console.warn(t)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"delete",value:async function(){let t=Array.from(arguments);if(!f(1===t.length?t[0].name:t[0],e))return i.apply(this,t)},enumerable:!0}),a({context:globalThis.cookieStore,property:"prototype",value:globalThis.CookieStore.prototype,enumerable:!1}),a({context:globalThis,property:"cookieStore",value:globalThis.cookieStore,enumerable:!0}),{get:r,getAll:o,set:n,delete:i}}(e,void 0),cookie:g()}),P="tbReady",C="security_overrideGlobals",{experiments:D,siteFeaturesConfigs:M,accessTokensUrl:O}=window.viewerModel,$={},j=(t=b(T,E),S(x,"specs.thunderbolt.browserCacheReload")&&(b(k,E)||t?m("removeItem"):function(){if("undefined"!=typeof window){let e=performance.getEntriesByType("navigation")[0];return"back_forward"===(e?.type||"")}return!1}()&&function(){let{counter:e}=function(){let e=m("getItem");if(e){let[t,r]=e.split("-"),o=r?parseInt(r,10):0;if(o>=3){let e=t?Number(t):0;if(Date.now()-e>6e4)return{counter:0}}return{counter:o}}return{counter:0}}();e<3?(function(e=1){m("setItem",`${Date.now()}-${e}`)}(e+1),window.location.reload()):console.error("ATS: Max reload attempts reached")}()),r=h(T),o=h(T,location.hostname),E.set.call(document,r),E.set.call(document,o),t);j&&($["client-binding"]=j);let A=fetch;addEventListener(P,function e(t){let{logger:r}=t.detail;try{window.tb.init({fetch:A,fetchHeaders:$})}catch(t){let e=Error("TB003");r.meter(`${C}_${e.message}`,{paramsOverrides:{errorType:C,eventString:e.message}}),window?.viewerModel?.mode.debug&&console.error(t)}finally{removeEventListener(P,e)}}),S(D,"specs.thunderbolt.hardenFetchAndXHR")||(window.fetchDynamicModel=()=>M.sessionManager.isRunningInDifferentSiteContext?Promise.resolve({}):fetch((()=>{try{let e="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope,t=globalThis?.parent!==globalThis,r=new URL(O,location.href);return(t||e)&&(r.searchParams.set("ifr",String(t)),r.searchParams.set("worker",String(e))),r.href}catch{return O}})(),{credentials:"same-origin",headers:$}).then(function(e){if(!e.ok)throw Error(`[${e.status}]${e.statusText}`);return e.json()}),window.dynamicModelPromise=window.fetchDynamicModel())})();
//# sourceMappingURL=https://static.parastorage.com/services/wix-thunderbolt/dist/handleAccessTokens.inline.3250797b.bundle.min.js.map</script>

<!-- END handleAccessTokens bundle -->

<!-- BEGIN overrideGlobals bundle -->


In [ ]:
cont = page.content.decode('utf-8')
print(cont)

<!DOCTYPE html>
<html lang="id">
<head>

  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1" id="wixDesktopViewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Wix.com Website Builder"/>

  <link rel="icon" sizes="192x192" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>
  <link rel="shortcut icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>
  <link rel="apple-touch-icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_180%2Ch_180%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png" type="image/png"/>

  <!-- Safari Pinned Tab Icon -->
  <!-- <link rel="mask-icon" href="https://static.wixstatic.com/media/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/f0ce13_c2d72981dc604843b9de5dd4e57291a6%7Emv2.png"> -->

  <!-- Segmenter Polyfill -->
  <script>
    if (!window.Intl || !window.Intl.Segmenter) {
      (function() {
        var script = document.createElement('script');
        script.src = 'https://static.parastorage.com/unpkg/@formatjs/intl-segmenter@11.7.10/polyfill.iife.js';
        document.head.appendChild(script);
      })();
    }
  </script>

  <!-- Legacy Polyfills -->
  <script nomodule="" src="https://static.parastorage.com/unpkg/core-js-bundle@3.2.1/minified.js"></script>
  <script nomodule="" src="https://static.parastorage.com/unpkg/focus-within-polyfill@5.0.9/dist/focus-within-polyfill.js"></script>

  <!-- Performance API Polyfills -->
  <script>
  (function () {
    var noop = function noop() {};
    if ("performance" in window === false) {
      window.performance = {};
    }
    window.performance.mark = performance.mark || noop;
    window.performance.measure = performance.measure || noop;
    if ("now" in window.performance === false) {
      var nowOffset = Date.now();
      if (performance.timing && performance.timing.navigationStart) {
        nowOffset = performance.timing.navigationStart;
      }
      window.performance.now = function now() {
        return Date.now() - nowOffset;
      };
    }
  })();
  </script>


    <!-- Essential Viewer Model -->
    <script type="application/json" id="wix-essential-viewer-model">{"fleetConfig":{"fleetName":"thunderbolt-isolated-renderer","type":"GA","code":0},"mode":{"qa":false,"enableTestApi":false,"addAllServices":false,"debug":false,"ssrIndicator":false,"ssrOnly":false,"siteAssetsFallback":"enable","versionIndicator":false},"componentsLibrariesTopology":[{"artifactId":"editor-elements","namespace":"wixui","url":"https:\/\/static.parastorage.com\/services\/editor-elements\/1.15516.0"},{"artifactId":"editor-elements","namespace":"dsgnsys","url":"https:\/\/static.parastorage.com\/services\/editor-elements\/1.15516.0"}],"siteFeaturesConfigs":{"sessionManager":{"isRunningInDifferentSiteContext":false}},"language":{"userLanguage":"id"},"siteAssets":{"clientTopology":{"mediaRootUrl":"https:\/\/static.wixstatic.com","scriptsUrl":"static.parastorage.com","staticMediaUrl":"https:\/\/static.wixstatic.com\/media","staticAudioUrl":"https:\/\/music.wixstatic.com\/mp3","moduleRepoUrl":"https:\/\/static.parastorage.com\/unpkg","fileRepoUrl":"https:\/\/static.parastorage.com\/services","viewerAppsUrl":"https:\/\/viewer-apps.parastorage.com","viewerAssetsUrl":"https:\/\/viewer-assets.parastorage.com","siteAssetsUrl":"https:\/\/siteassets.parastorage.com","pageJsonServerUrls":["https:\/\/pages.parastorage.com","https:\/\/staticorigin.wixstatic.com","https:\/\/www.historia.id","https:\/\/fallback.wix.com\/wix-html-editor-pages-webapp\/page"],"pathOfTBModulesInFileRepoForFallback":"wix-thunderbolt\/dist\/"}},"siteFeatures":["accessibilityBrowserZoom","appMonitoring","assetsLoader","businessLogger","captcha","clickHandlerRegistrar","clientSdk","codeEmbed","commonConfig","componentsRegistry","consentPolicy","cookiesManager","customCss","customUrlMapper","cyclicTabbing","domSelectors","domStore","dynamicPages","environmentWixCodeSdk","environment","externalServices","lightbox","locationWixCodeSdk","mpaNavigation","multilingual","navigationManager","navigationPhases","ooi","pages","panorama","protectedPages","renderer","reporter","routerFetch","router","scrollRestoration","seoWixCodeSdk","seo","sessionManager","siteMembersWixCodeSdk","siteMembers","siteScrollBlocker","siteWixCodeSdk","speculationRules","ssrCache","stores","structureApi","thunderboltInitializer","tpaCommons","translations","usedPlatformApis","warmupData","windowMessageRegistrar","windowWixCodeSdk","wixCustomElementComponent","wixEmbedsApi","componentsLoader","componentsReact","platform"],"site":{"externalBaseUrl":"https:\/\/www.historia.id","isSEO":false},"media":{"staticMediaUrl":"https:\/\/static.wixstatic.com\/media","mediaRootUrl":"https:\/\/static.wixstatic.com\/","staticVideoUrl":"https:\/\/video.wixstatic.com\/","userDomainMediaPrefixes":[]},"requestUrl":"https:\/\/www.historia.id\/articles\/categories\/politik","rollout":{"siteAssetsVersionsRollout":false,"isDACRollout":0,"isTBRollout":false},"commonConfig":{"brand":"studio","host":"VIEWER","bsi":"","consentPolicy":{},"consentPolicyHeader":{},"siteRevision":"3694","renderingFlow":"NONE","language":"id","locale":"id-id"},"interactionSampleRatio":0.01,"accessTokensUrl":"https:\/\/www.historia.id\/_api\/v1\/access-tokens","experiments":{"specs.thunderbolt.hardenFetchAndXHR":true,"specs.thunderbolt.securityExperiments":true,"specs.thunderbolt.allowWebpAvifTransforms":true,"specs.thunderbolt.browserCacheReload":true,"specs.thunderbolt.browserZoomMobileOnloadDetection":true}}</script>
    <script>window.viewerModel = JSON.parse(document.getElementById('wix-essential-viewer-model').textContent)</script>


  <!-- Globals Definitions -->
  <script>
    (function () {
      var now = Date.now()
      var activationStart = 0
      try {
        var navEntry = performance.getEntriesByType('navigation')[0];
        if (navEntry && navEntry.activationStart > 0) {
          activationStart = navEntry.activationStart;
        }
      } catch (e) {}
      window.initialTimestamps = {
        initialTimestamp: now,
        initialRequestTimestamp: Math.round(performance.timeOrigin ? performance.timeOrigin + activationStart : now - performance.now() + activationStart)
      }

      window.thunderboltTag = "libs-releases-GA-local"
      window.thunderboltVersion = "1.17950.0"
    })();
  </script>

  <script>
    window.commonConfig = viewerModel.commonConfig
  </script>


  <!-- BEGIN handleAccessTokens bundle -->

  <script data-url="https://static.parastorage.com/services/wix-thunderbolt/dist/handleAccessTokens.inline.3250797b.bundle.min.js">(()=>{"use strict";let e,t,r,o;var n={},i={};function l(e){var t=i[e];if(void 0!==t)return t.exports;var r=i[e]={exports:{}};return n[e](r,r.exports,l),r.exports}function a(e){let{context:t,property:r,value:o,enumerable:n=!0}=e,i=e.get,l=e.set;if(!r||void 0===o&&!i&&!l)return Error("property and value are required");let a=t||globalThis,s=a?.[r],u={};if(void 0!==o)u.value=o;else{if(i){let e=c(i);e&&(u.get=e)}if(l){let e=c(l);e&&(u.set=e)}}let p={...u,enumerable:n||!1,configurable:!1};void 0!==o&&(p.writable=!1);try{Object.defineProperty(a,r,p)}catch(e){return e instanceof TypeError?s:e}return s}function c(e,t){return"function"==typeof e?e:e?.async===!0&&"function"==typeof e.func?t?async function(t){return e.func(t)}:async function(){return e.func()}:"function"==typeof e?.func?e.func:void 0}l.rv=()=>"1.6.8",l.ruid="bundler=rspack@1.6.8";try{a({property:"strictDefine",value:a})}catch{}try{a({property:"defineStrictObject",value:function e(t){let{context:r,property:o,propertiesToExclude:n=[],skipPrototype:i=!1,hardenPrototypePropertiesToExclude:l=[]}=t;if(!o)return Error("property is required");let c=(r||globalThis)[o],p={},f=u(r,o);c&&("object"==typeof c||"function"==typeof c)&&Reflect.ownKeys(c).forEach(e=>{if(!n.includes(e)&&!s.includes(e)){let t=u(c,e);if(t&&(t.writable||t.configurable)){let{value:r,get:o,set:n,enumerable:i=!1}=t,l={};void 0!==r?l.value=r:o?l.get=o:n&&(l.set=n);try{let t=a({context:c,property:e,...l,enumerable:i});p[e]=t}catch(r){if(r instanceof TypeError)try{p[e]=t.value||t.get||t.set}catch{}else throw r}}}});let d={originalObject:c,originalProperties:p};if(!i&&c?.prototype!==void 0){let t=e({context:c,property:"prototype",propertiesToExclude:l,skipPrototype:!0});t instanceof Error||(d.originalPrototype=t?.originalObject,d.originalPrototypeProperties=t?.originalProperties)}return a({context:r,property:o,value:c,enumerable:f?.enumerable}),d}})}catch{}try{a({property:"defineStrictMethod",value:function(e,t){let r=(t||globalThis)[e],o=u(t||globalThis,e);return r&&o&&(o.writable||o.configurable)?(Object.freeze(r),a({context:globalThis,property:e,value:r})):r}})}catch{}var s=["toString","toLocaleString","valueOf","constructor","prototype"];function u(e,t){if(!(!e||!t))try{return Reflect.getOwnPropertyDescriptor(e,t)}catch{return}}function p(e){if("string"!=typeof e)return e;try{return decodeURIComponent(e).toLowerCase().trim()}catch{return e.toLowerCase().trim()}}function f(e,t){let r="";if("string"==typeof e)r=e.split("=")[0]?.trim()||"";else{if(!e||"string"!=typeof e.name)return!1;r=e.name}return t.has(p(r)||"")}function d(e,t){return("string"==typeof e?e.split(";").map(e=>e.trim()).filter(e=>e.length>0):e||[]).filter(e=>!f(e,t))}var y=null;function g(){return null===y&&(y=typeof Document>"u"?void 0:Object.getOwnPropertyDescriptor(Document.prototype,"cookie")),y}let b=(e,t)=>{try{let r=t?t.get.call(document):document.cookie;return r.split(";").map(e=>e.trim()).filter(t=>t?.startsWith(e))[0]?.split("=")[1]}catch(e){return""}},h=(e="",t="",r="/")=>`${e}=; ${t?`domain=${t};`:""} max-age=0; path=${r}; expires=Thu, 01 Jan 1970 00:00:01 GMT`;function m(e,t){try{return sessionStorage[e]("reload",t||"")}catch(e){console.error("ATS: Error calling sessionStorage:",e)}}var v=["true","b","c","new","enabled"];let w=[],S=(e,t)=>{let r;return w.includes(t)||!0===(r=e[t])||"string"==typeof r&&v.includes(r.toLowerCase())},T="client-session-bind",k="sec-fetch-unsupported",{experiments:x}=window.viewerModel,{cookie:E}=(e=new Set([T,"client-binding",k,"svSession","smSession","server-session-bind","wixSession2","wixSession3"].map(e=>e.toLowerCase())),a({context:document,property:"cookie",set:{func:t=>{var r,o;let n,i;return r=document,o=void 0,n=g(),i=p(t.split(";")[0]||"")||"",void([...e].every(e=>!i.startsWith(e.toLowerCase()))&&n?.set?n.set.call(r,t):o&&console.warn(o))}},get:{func:()=>(function(e,t){let r=g();if(!r?.get)throw Error("Cookie descriptor or getter not available");return d(r.get.call(e),t).join("; ")})(document,e)},enumerable:!0}),{cookieStore:function(e,t){if(!globalThis?.cookieStore)return;let r=globalThis.cookieStore.get.bind(globalThis.cookieStore),o=globalThis.cookieStore.getAll.bind(globalThis.cookieStore),n=globalThis.cookieStore.set.bind(globalThis.cookieStore),i=globalThis.cookieStore.delete.bind(globalThis.cookieStore);return a({context:globalThis.CookieStore.prototype,property:"get",value:async function(t){return f(("string"==typeof t?t:t.name)||"",e)?null:r.call(this,t)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"getAll",value:async function(){let t=await o.apply(this,Array.from(arguments));return d(t,e)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"set",value:async function(){let r=Array.from(arguments);if(!f(1===r.length?r[0].name:r[0],e))return n.apply(this,r);t&&console.warn(t)},enumerable:!0}),a({context:globalThis.CookieStore.prototype,property:"delete",value:async function(){let t=Array.from(arguments);if(!f(1===t.length?t[0].name:t[0],e))return i.apply(this,t)},enumerable:!0}),a({context:globalThis.cookieStore,property:"prototype",value:globalThis.CookieStore.prototype,enumerable:!1}),a({context:globalThis,property:"cookieStore",value:globalThis.cookieStore,enumerable:!0}),{get:r,getAll:o,set:n,delete:i}}(e,void 0),cookie:g()}),P="tbReady",C="security_overrideGlobals",{experiments:D,siteFeaturesConfigs:M,accessTokensUrl:O}=window.viewerModel,$={},j=(t=b(T,E),S(x,"specs.thunderbolt.browserCacheReload")&&(b(k,E)||t?m("removeItem"):function(){if("undefined"!=typeof window){let e=performance.getEntriesByType("navigation")[0];return"back_forward"===(e?.type||"")}return!1}()&&function(){let{counter:e}=function(){let e=m("getItem");if(e){let[t,r]=e.split("-"),o=r?parseInt(r,10):0;if(o>=3){let e=t?Number(t):0;if(Date.now()-e>6e4)return{counter:0}}return{counter:o}}return{counter:0}}();e<3?(function(e=1){m("setItem",`${Date.now()}-${e}`)}(e+1),window.location.reload()):console.error("ATS: Max reload attempts reached")}()),r=h(T),o=h(T,location.hostname),E.set.call(document,r),E.set.call(document,o),t);j&&($["client-binding"]=j);let A=fetch;addEventListener(P,function e(t){let{logger:r}=t.detail;try{window.tb.init({fetch:A,fetchHeaders:$})}catch(t){let e=Error("TB003");r.meter(`${C}_${e.message}`,{paramsOverrides:{errorType:C,eventString:e.message}}),window?.viewerModel?.mode.debug&&console.error(t)}finally{removeEventListener(P,e)}}),S(D,"specs.thunderbolt.hardenFetchAndXHR")||(window.fetchDynamicModel=()=>M.sessionManager.isRunningInDifferentSiteContext?Promise.resolve({}):fetch((()=>{try{let e="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope,t=globalThis?.parent!==globalThis,r=new URL(O,location.href);return(t||e)&&(r.searchParams.set("ifr",String(t)),r.searchParams.set("worker",String(e))),r.href}catch{return O}})(),{credentials:"same-origin",headers:$}).then(function(e){if(!e.ok)throw Error(`[${e.status}]${e.statusText}`);return e.json()}),window.dynamicModelPromise=window.fetchDynamicModel())})();
//# sourceMappingURL=https://static.parastorage.com/services/wix-thunderbolt/dist/handleAccessTokens.inline.3250797b.bundle.min.js.map</script>

<!-- END handleAccessTokens bundle -->

<!-- BEGIN overrideGlobals bundle -->


In [ ]:
from bs4 import BeautifulSoup

In [ ]:
import cloudscraper
from bs4 import BeautifulSoup

scraper = cloudscraper.create_scraper(browser={'browser': 'chrome', 'platform': 'windows', 'mobile': False})

page = scraper.get('https://www.historia.id/articles/categories/politik')

print("Status Code:", page.status_code)

bs = BeautifulSoup(page.text, 'html.parser')

Status Code: 200

In [ ]:
if bs.title:
    print(bs.title)
else:
    print("Tag title diblokir oleh server")

<title>Politik</title>

In [ ]:
if bs.title:
    print(bs.title.name)

title

In [ ]:
if bs.title:
    print(bs.title.text)

Politik

In [ ]:
bs.div

<div id="SITE_CONTAINER"><style id="STYLE_OVERRIDES_ID">#comp-mnpnfj6h_r_comp-ml93qt6r{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93qt7q8{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93qt7u3{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93qt7y6{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93qt8n14{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93qt8i3{visibility:hidden !important;} #comp-mnpnfj6h_r_comp-ml93rv30{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnpnfj6h_r_comp-ml93rv3612{visibility:hidden !important;} #comp-mnppn8fm{visibility:hidden !important;} #comp-mnppnmdd7{visibility:hidden !important;} #comp-mnppnmdf{visibility:hidden !important;} #comp-mnppnmdj9{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-lxn6iul9{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnpnj1iq_r_comp-ml93vqsp{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__item1{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__item-j9ples3e{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__item-j9plerjk{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__67c80f8e844d86c93bebfbdf{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6ab20c4a703293e42173196b{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6ab104cabcd37dc9f1038373{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aacf13ad351bc6bc516dfb5{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aacb9bb59ac8bae3b00ce3b{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aaba3bc3663585669c6edf0{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aaa826f435fe3ebd8e23f0d{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aaa680c72df054056884e2e{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aaa6ee9492c8c41baf875fb{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa90cbbe099c7cfc27a85f7{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa8dd4f9ede246322ec3ec5{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa7d956f688f98da0f2355c{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa4057d6b6b040961d8e0f6{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa55e5edd58bcb58cb73fb2{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa4e1de571318e8c9e61f34{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6aa22a8fe2747afb47ebfeb6{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6a9e7945ff2777f8cf453046{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6a9f692a810c122bb1cfc465{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6a9e88c3ff2777f8cf4551b6{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;} #comp-mnppnmdj9__6a9e5e92c15a95c04c957627{visibility:hidden !important;overflow:clip !important;height:0 !important;width:0 !important;min-width:0 !important;min-height:0 !important;margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;padding:0 !important;position:absolute !important;margin-top:0 !important;}</style><div class="main_MF" id="main_MF"><div aria-label="top of page" class="qe3oTb ignore-focus SCROLL_TO_TOP" id="SCROLL_TO_TOP" role="region" tabindex="-1"><span class="TvbeET">top of page</span></div><div class="site-root" id="site-root"><div class="masterPage css-editing-scope" id="masterPage"><div class="Y3K28_ SITE_PAGES" id="SITE_PAGES"><div class="ETqrjz theme-vars uzwgr" id="uzwgr"><div class="g0IvTF wixui-page" data-testid="page-bg"></div><div><div class="uzwgr-overflow-wrapper ku1hVK" data-testid="responsive-container-overflow"><div class="uzwgr-container" data-testid="responsive-container-content" role="group" tabindex="-1"><!--$--><div class="comp-mnpnfj6h-pinned-layer QED8q1" id="comp-mnpnfj6h-pinned-layer"><header class="comp-mnpnfj6h S829f_ comp-mnpnfj6h-container" id="comp-mnpnfj6h" slots="[object Object]" wix="[object Object]"><section class="ke5pl1 comp-mnpnfj6h_r_comp-ml93pd7i ke5pl1 wixui-header wixui-header header fwXYgt" data-block-level-container="Section" data-testid="section-container" id="comp-mnpnfj6h_r_comp-ml93pd7i" tabindex="-1"><div class="QG9w8P" data-hook="bgLayers" data-motion-part="BG_LAYER comp-mnpnfj6h_r_comp-ml93pd7i" id="bgLayers_comp-mnpnfj6h_r_comp-ml93pd7i"><div class="LNYVZi ayCf9D" data-testid="colorUnderlay"></div><div class="ROWgFb" data-motion-part="BG_MEDIA comp-mnpnfj6h_r_comp-ml93pd7i" id="bgMedia_comp-mnpnfj6h_r_comp-ml93pd7i"></div></div><div class="comp-mnpnfj6h_r_comp-ml93pd7i-container" data-testid="responsive-container-content" role="group"><!--$--><div class="HFEOE3 NaeT1r comp-mnpnfj6h_r_comp-ml93qt6d-container comp-mnpnfj6h_r_comp-ml93qt6d wixui-box wixui-boxMenu boxMenu" dir="ltr" id="comp-mnpnfj6h_r_comp-ml93qt6d" role=""><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-box wixui-boxMenu boxMenu"></div><!--$--><div class="HFEOE3 NaeT1r comp-mnpnfj6h_r_comp-ml93qt6h wixui-box" dir="ltr" id="comp-mnpnfj6h_r_comp-ml93qt6h" role=""><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-box"></div><div class="comp-mnpnfj6h_r_comp-ml93qt6h-container" data-testid="responsive-container-content" role="group"><!--$--><div class="comp-mnpnfj6h_r_comp-ml93qt6j3" data-semantic-classname="button" dir="inherit" id="comp-mnpnfj6h_r_comp-ml93qt6j3"><a aria-label="Historia.ID" class="WZxFET comp-mnpnfj6h_r_comp-ml93qt6j3-styleId__root wixui-button OOhWpA" data-testid="linkElement" href="https://www.historia.id" target="_self"><span class="UPWJFm"><span class="QeinDR wixui-button__label" data-testid="stylablebutton-label">Go</span><span aria-hidden="true" class="vwUNxR wixui-button__icon" data-testid="stylablebutton-icon"><span>
<svg data-bbox="110 133.355 3720.999 766.645" data-type="color" height="330.881" viewbox="0 0 3941 1034" width="1261.123" xmlns="http://www.w3.org/2000/svg">
<g>

In [ ]:
if bs.a:
    print(bs.a)
else:
    print("Tag <a> tidak ditemukan")

<a aria-label="Historia.ID" class="WZxFET comp-mnpnfj6h_r_comp-ml93qt6j3-styleId__root wixui-button OOhWpA" data-testid="linkElement" href="https://www.historia.id" target="_self"><span class="UPWJFm"><span class="QeinDR wixui-button__label" data-testid="stylablebutton-label">Go</span><span aria-hidden="true" class="vwUNxR wixui-button__icon" data-testid="stylablebutton-icon"><span>
<svg data-bbox="110 133.355 3720.999 766.645" data-type="color" height="330.881" viewbox="0 0 3941 1034" width="1261.123" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M110 323h283v21h-85v240h245V344h-85v-21h283v21h-84v521h85v21H468v-20h85V606H308v259h85v21H110v-20h84V344h-84Zm813-189.56c4.75-.38 15.2.91 20 1.98 51.24 11.48 69.64 76.52 34.83 114.57C967.2 261.6 947.87 270.81 932 271h-12c-7.52-.09-15.02-2.09-22-4.81-37.08-14.48-52.07-57.93-35.51-93.19 9.46-20.14 27.91-33.91 49.51-38.33ZM784 323h198v542h85v21H784v-21h85V344h-85zm317 445h30c2.13 0 5.58-.25 7.37.99 1.73 1.22 3.4 5.07 4.39 7.01l7.44 13c9.18 15.11 27.56 38.35 40.8 49.7 51.55 44.18 143.12 61.05 192.95 5.3 7.28-8.15 12.16-16.82 15.99-27 3.55-9.45 6.04-25.87 6.06-36v-14c-.02-11.2-2.66-20.61-6.58-31-8.78-23.27-21.59-40.05-43.42-52.72-25.96-15.05-51.74-21.52-80-30.3-23.66-7.36-49.45-16.51-72-26.68-25.36-11.43-46.85-23.05-64.55-45.3-18.81-23.64-26.67-53.48-29.62-83l-.83-9c-.19-16.73-.37-28.29 2.43-45 7.03-41.87 26.54-74.74 59.57-101.54 16.49-13.38 36.01-21.79 56-28.46 15.9-5.3 34.16-9.97 51-10h20c17.02.2 40.18 5.33 56 11.6 10.7 4.25 28.08 13.79 39 13.36 10.5-.41 17.24-4.91 24-6.43 3.71-.84 14.58-.53 19-.53v147h-16c-.93-11.4-6.88-30.07-10.95-41-14.75-39.58-42.69-84.56-85.05-97.97-12.37-3.92-33.91-6.05-47-6.03-46.2.07-95.06 27.07-110.66 72-2.86 8.26-5.23 17.2-5.34 26-.3 25.66 9.93 53.68 31 69.49 9.32 6.99 37.97 18.8 50 23.93 68.31 29.14 159 45.27 211.99 99.58 11.73 12.03 21.95 28.41 28.21 44 8.54 21.28 11.06 44.22 10.8 67l-.91 10c-5.38 73.56-61.07 131.31-129.09 154-15.45 5.15-36.74 9.97-53 10h-23c-24.3-.04-51.1-8.03-74-15.67l-42-14.66c-7.19-2.35-19.59-6-27-5.58-6.93.4-14.46 1.84-19.98 6.3-5.09 4.1-5.61 7.74-8.41 9.04-1.99.92-11.82.57-14.61.57zm1908-634.56c5.68-.45 15.41.97 21 2.44 44.02 11.61 65.19 64.28 41.54 103.12-11.4 18.71-33.5 31.9-55.54 32h-11c-7.22-.09-14.33-1.91-21-4.6-38.28-15.46-53.35-58.99-35.03-95.4 8.05-16.01 22.95-28.8 40.03-34.25 8.24-2.64 12.1-2.24 20-3.31M2875 323h198v542h86v21h-284v-21h85V344h-85zM1552 149c5.57 1.04 10.66 3.8 16 5.66 10.74 3.72 23.58 7.2 35 7.34 13.63.16 27.44-2.49 40-7.87l23-11.13v180h170v21h-170v433l.91 10c2.15 30.67 10.55 64.42 41.09 78.68 11.84 5.53 28.02 7.47 41 7.32 31.54-.37 58.79-24.02 72.74-51 6.47-12.51 9.77-24.61 13.68-38 .92-3.15 2.84-12.14 5.86-13.36 3.04-1.24 14.02 2.52 17.72 3.36-1.26 8.17-8.15 25.97-11.58 34-5.81 13.59-16.84 33.07-26.59 44-31.11 34.83-76.46 47.53-121.83 47l-10-.91c-51.9-3.79-98.9-34.39-122.25-81.09-7.95-15.91-13.72-35.09-13.75-53V344h-85v-21h84zm1033 278c3.78-3.96 6.56-11.85 8.86-17l10.14-19c14-24.5 31.19-47.55 54-64.52 23.86-17.76 53.23-27.43 83-27.48 39.69-.06 70.81 10.95 95.37 44 5.48 7.37 11.25 17.32 14.29 26 3.35 9.6 6.22 23.86 6.34 34v14c-.04 28.11-13.06 61.67-38 76.55-31.9 19.02-81.37 13.08-93.97-26.55-1.91-6.01-3-11.69-3.03-18-.06-12.34 1.28-21.95 7.31-33 10.92-20.01 27.32-28.32 21.67-54-.93-4.24-2.22-7.2-4.29-11-2.35-4.3-5.22-8.49-8.73-11.91-20.21-19.67-48.72-2.75-66.96 11.04-33.19 25.09-58.01 60.4-73.4 98.87-4.78 11.96-11.58 29.22-11.6 42v374h84v21h-283v-21h85V344h-85v-21h198zm-466.999-124.791-10.998.958-23.004 3.253c-21.64 3.91-43.02 10.712-63 19.892-79.69 36.58-140.437 107.547-164.417 191.686-5.63 19.75-10.343 43.482-10.583 64.002l-1.001 13 1 21.997c.29 24.06 9.88 62.344 18.42 85.004 19.16 50.79 56.6 100.81 99.58 133.77 14.999 11.5 31.134 21.04 48.004 29.48 12.1 6.05 27.106 12.72 39.996 16.73 20.769 6.46 41.401 9.628 63 11.108l10.004.91h7l9.998-.91c36.37-2.49 62.863-9.57 96.002-24.78 81.57-37.45 142.678-113.552 164.368-200.311 4.13-16.52 6.55-33.05 7.72-50L2411 608c.42-36.04-3.317-66.5-14.337-101-24.83-77.69-82.093-140.963-154.663-177.252-31.72-15.86-64.7-24.407-100-26.837l-10.998-.702zm-4.999 20.788c42.76-.5 77.78.522 112 30.292 45.279 39.38 56.67 105.944 62.17 162.713l1.831 31.995.995 14.001V639l-.995 15.003V658l-4.584 47.998c-.44 3.04-.568 15.981-6.158 12.921-3.07-1.68-5.392-12.287-6.592-15.917l-14.691-49-15.497-55.004c-.91-6.01 1.951-7.41 2.411-13 .74-8.78-4.653-10.067-5.933-14.997-.97-3.41 1.3-6.129 0-10.998-1.99-8.04-8.609-7.984-11.279-16.004l-21.032-83.996-5.768-25c-.58-2.46-2.468-9.874-1.978-11.994.71-3.06 3.895-5.127 6.085-7.177 6.75-6.31 20.68-24.232 4.01-28.302-2.34-.57-5.565-.569-7.995-.519-16.91.39-51.355 8.511-67.005 15.27-4.66 2.01-20.238 8.697-16.918 15.577 3.049 6.32 18.45 2.634 23.92 1.624 2.05-.49 7.461-2.08 8.831 0 1.47 2.42-2.301 4.2-3.851 4.9l-19.977 6.946c-23.37 7.79-39.702 11.472-64.002 14.942-5.43.77-19.622 2.937-23.382-1.703-3.13-3.85 1.739-8.855 4.419-11.395 7.37-6.98 20.021-14.473 28.961-19.592 27.07-15.49 71.973-28.331 103.003-32.581l26-3.168c2.42-.27 7.718-.92 8.228-3.93.69-4.13-5.567-4.73-8.227-4.92l-12-.94L2172 369l-39.001 4.577c-35.39 5.49-61.646 12.513-94.996 25.623l-30.004 13.049-19.995 9.753c2.36-10.35 8.464-22.77 13.714-32 19.9-34.99 47.85-56.242 87.28-64.002 6.3-1.24 17.745-2.923 24.005-3.003m66.999 111.005 15.716 51 17.81 62.995-2.136 18.005 5.847 10.999 1.215 13.989 10.107 13.013 4.321 16.998 9.998 39.996 13.12 56.006c-4.42 1.24-7.839 1.686-10.199-3.064l-8.862-26.94c-4.25-11.09-11.823-23.686-19.153-32.996-12.23-15.53-29.859-25.666-45.788-37.006-7.43-5.29-19.168-12.726-22.858-20.996-2.97-5.82-1.71-11.148 0-16.998l14.002-30.005c4.8-10.78 10.145-21.466 13.195-32.996 3.77-16.43 2.57-32.475 0-49.005l-2.935-19c-.47-2.34-1.603-6.589-.763-8.789 1.12-2.95 4.67-4.206 7.36-5.206m-22.004 12 5.573 28.997c2.14 12.77 2.431 30.5-.989 43-5 18.26-12.971 31.033-19.781 48.003-3.47 8.64-7.428 19.588-5.268 28.998 2.11 9.22 9.398 15.95 16.468 21.6l38 28.693c25.45 22.13 29.34 42.095 38.14 72.705 2.27 7.89 7.821 21.254 4.871 29.004-6.07 15.94-29.993 27.39-45.013 33.19-10.81 4.17-31.45 8.668-43 8.808-11.84.13-30.64-.918-39.66-9.528-4.78-4.56-6.49-16.934-7.99-23.474-2.839-12.36-9.29-34.326-9.35-45.996v-14.001c.08-17.52 12.591-42.553 19.861-59.003 3.76-8.51 8.07-17.596 8.82-26.996.92-11.62-8.261-21.642-16.681-28.332l-31-23.321c-5.99-4.62-12.548-9.18-16.998-15.35 8.98 1.69 10.744 2.037 18 2.001 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834l-3.205-13.977c-.71-4.81 2.182-5.25 6.202-5.89l22.998-3.73c21.53-4.31 43.191-9.32 64.001-16.4zm-183.996 33.996c1.86.62 3.778 1.053 5.158 2.563 1.52 1.66 3.069 7.106 3.839 9.436l6.67 22.003 15.754 53.998 9.119 33.002c1.47 8.66-3.763 10.57-2.143 17.999 1.1 5.11 4.89 7.409 5.92 10.999s-1.79 8.221 1.13 14.001c2.93 5.78 7.054 5.671 9.424 11.041l6.5 23.963 12 48.998 7.28 31 3.205 15.96c-.04 4.78-4.758 7.836-7.818 11.036-4.05 4.24-8.918 11.024-9.668 17.004-.76 5.99 3.19 11.086 7.63 14.606 7.41 5.88 24.562 9.283 34.002 9.393H2086l8.002.678 10.999-.678 25-1.849c30.48-3.64 61.102-11.558 90.002-21.838L2264.998 784c-2.02 7.1-7.028 16.508-10.718 22.998-17.27 30.37-42.621 50.971-76.281 60.571-12.31 3.52-24.33 4.648-37 5.518l-9.997.91h-6l-10.004-1.038h-7.995c-34.71-3.44-66.664-17.068-89.704-43.958-18.71-21.83-30.26-51.364-37.17-79.003C1967 697.479 1965.92 642.81 1966 589l1.001-16.998v-24.005l1.91-27.997c.68-9.68 2.451-31.382 5.091-40.002m31.159 2.081c1.73.025 3.339.579 4.419 2.234l9.112 26.685c3.71 10.18 11.637 23.47 18.317 32 11.96 15.25 31.032 27.111 46.99 38.281 7.5 5.25 18.965 12.212 22.645 20.722 4.83 11.2-5.614 28.711-10.334 39.001l-15.869 35.999c-4.43 14.65-4.457 24.091-4.437 39.001.02 9.82 2.186 19.458 4.346 28.998.58 2.55 3.004 12.998 2.594 14.898-.71 3.33-4.12 4.273-6.94 5.103L2056.289 701l-13.727-49c-.96-6.42 4.31-9.718 2.46-16.998-1.33-5.25-5.092-7.174-5.982-11.004-.93-3.95 2.541-7.606-1.129-13.996-3.41-5.95-7.6-5.524-9.93-12.023l-13.63-53.98-14.349-60.998c1.575-.445 3.426-.947 5.158-.922" data-color="1" fill="#000000"></path>
<path d="M3517.98 135.107c-3.32-.33-6.848.145-8.838 3.125l-4.81 13.77-9.002 26L3463.69 268l-18.11 53.003-10.919 32-35.003 101.996-63.318 182L3301.69 738l-25 72.003-8.88 26.001-6.482 18.994c-1.12 3.25-2.348 7.002-5.518 8.832-2.41 1.39-6.067 1.172-8.807 1.172h-56.006v21.002H3368V865h-89.002l37.665-107 7-20.002c1.46-4.2 2.465-8.731 6.385-11.401 2.73-1.86 5.814-1.59 8.954-1.6h252.001c3.27.01 7.02-.29 9.79 1.74 3.07 2.25 4.366 6.79 5.536 10.26L3613.33 758l35.669 107h-76.996v21.003h258.996V865H3777c-3.23-.01-7.047.29-9.777-1.74-2.94-2.19-4.105-6.89-5.225-10.26l-7-22.003L3718.328 721l-52.655-158.002-20.331-59.997L3605.327 382l-24.518-72.998L3566.998 268l-30.328-92-10.34-31c-1.64-4.87-2.439-9.304-8.349-9.894M3471.001 306l8.277 27.002 21.38 68L3561.022 594l21.997 70L3595 703.002h-259.002L3363.33 621l62.34-184.002L3444 383l14.19-41.998zM2173 744c3.71-5.26 14.86-6.15 21-5.98 2.88.07 8.51.59 6.83 5.01-1.54 4.06-9.01 7.42-12.83 9.11-12.82 5.67-29.08 8.99-43 10.57-5.45.63-17.42-.52-15.31-8.71 1.61-6.22 10.94-11.05 16.31-13.75 16.67-8.39 29.76-10.65 48-12.42 3.49-.34 5.21-.91 9-.79 7.22.23 23.7 1.98 24.84 10.96 1.1 8.67-9.58 17.08-15.84 21.57-19.44 13.96-45.45 20.34-69 22.11-3.24.24-4.89-.37-8-.59-9.29-.68-24.27-2.1-24.96-14.09-.56-9.79 5.68-23.95 9.54-33 5.81-13.61 11.11-27.58 14.54-42 2.63-11.11 2.9-18.75 2.88-30-.01-6.69-.29-6.63-1.04-13-.32-1.76-1.03-4.86 0-6.38 3.7-4.84 5.77 4.4 5.97 6.38l1.07 30c-.19 16.23-6.73 37.77-12.42 53-2.06 5.5-9.07 21.99-8.27 27 1.32 8.25 10.1 8.99 16.69 9 20.09.03 40.08-4.47 58-13.78 4.81-2.5 9.17-5.19 12.89-9.2 1.23-1.32 3.16-3.12 2.15-5.09-2.32-4.52-14.55-5.15-19.04-4.84-11.3.77-24.41 4.28-35 8.23-6.81 2.54-12.49 4.73-17 10.68 12.6 3.06 38.81-4.65 50-11-6.98.57-11.06 2.95-18 1m-119-201.002c8.98 1.69 10.744 2.038 18 2.002 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834 4.987 19.762 10.576 32.92 21.997 44" data-color="2" fill="#d40000"></path>
</g>
</svg>
</span></span></span></a>

In [ ]:
bs.a.text

'Go\n\n\n\n\n\n\n'

In [ ]:
bs.find("a")

<a aria-label="Historia.ID" class="WZxFET comp-mnpnfj6h_r_comp-ml93qt6j3-styleId__root wixui-button OOhWpA" data-testid="linkElement" href="https://www.historia.id" target="_self"><span class="UPWJFm"><span class="QeinDR wixui-button__label" data-testid="stylablebutton-label">Go</span><span aria-hidden="true" class="vwUNxR wixui-button__icon" data-testid="stylablebutton-icon"><span>
<svg data-bbox="110 133.355 3720.999 766.645" data-type="color" height="330.881" viewbox="0 0 3941 1034" width="1261.123" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M110 323h283v21h-85v240h245V344h-85v-21h283v21h-84v521h85v21H468v-20h85V606H308v259h85v21H110v-20h84V344h-84Zm813-189.56c4.75-.38 15.2.91 20 1.98 51.24 11.48 69.64 76.52 34.83 114.57C967.2 261.6 947.87 270.81 932 271h-12c-7.52-.09-15.02-2.09-22-4.81-37.08-14.48-52.07-57.93-35.51-93.19 9.46-20.14 27.91-33.91 49.51-38.33ZM784 323h198v542h85v21H784v-21h85V344h-85zm317 445h30c2.13 0 5.58-.25 7.37.99 1.73 1.22 3.4 5.07 4.39 7.01l7.44 13c9.18 15.11 27.56 38.35 40.8 49.7 51.55 44.18 143.12 61.05 192.95 5.3 7.28-8.15 12.16-16.82 15.99-27 3.55-9.45 6.04-25.87 6.06-36v-14c-.02-11.2-2.66-20.61-6.58-31-8.78-23.27-21.59-40.05-43.42-52.72-25.96-15.05-51.74-21.52-80-30.3-23.66-7.36-49.45-16.51-72-26.68-25.36-11.43-46.85-23.05-64.55-45.3-18.81-23.64-26.67-53.48-29.62-83l-.83-9c-.19-16.73-.37-28.29 2.43-45 7.03-41.87 26.54-74.74 59.57-101.54 16.49-13.38 36.01-21.79 56-28.46 15.9-5.3 34.16-9.97 51-10h20c17.02.2 40.18 5.33 56 11.6 10.7 4.25 28.08 13.79 39 13.36 10.5-.41 17.24-4.91 24-6.43 3.71-.84 14.58-.53 19-.53v147h-16c-.93-11.4-6.88-30.07-10.95-41-14.75-39.58-42.69-84.56-85.05-97.97-12.37-3.92-33.91-6.05-47-6.03-46.2.07-95.06 27.07-110.66 72-2.86 8.26-5.23 17.2-5.34 26-.3 25.66 9.93 53.68 31 69.49 9.32 6.99 37.97 18.8 50 23.93 68.31 29.14 159 45.27 211.99 99.58 11.73 12.03 21.95 28.41 28.21 44 8.54 21.28 11.06 44.22 10.8 67l-.91 10c-5.38 73.56-61.07 131.31-129.09 154-15.45 5.15-36.74 9.97-53 10h-23c-24.3-.04-51.1-8.03-74-15.67l-42-14.66c-7.19-2.35-19.59-6-27-5.58-6.93.4-14.46 1.84-19.98 6.3-5.09 4.1-5.61 7.74-8.41 9.04-1.99.92-11.82.57-14.61.57zm1908-634.56c5.68-.45 15.41.97 21 2.44 44.02 11.61 65.19 64.28 41.54 103.12-11.4 18.71-33.5 31.9-55.54 32h-11c-7.22-.09-14.33-1.91-21-4.6-38.28-15.46-53.35-58.99-35.03-95.4 8.05-16.01 22.95-28.8 40.03-34.25 8.24-2.64 12.1-2.24 20-3.31M2875 323h198v542h86v21h-284v-21h85V344h-85zM1552 149c5.57 1.04 10.66 3.8 16 5.66 10.74 3.72 23.58 7.2 35 7.34 13.63.16 27.44-2.49 40-7.87l23-11.13v180h170v21h-170v433l.91 10c2.15 30.67 10.55 64.42 41.09 78.68 11.84 5.53 28.02 7.47 41 7.32 31.54-.37 58.79-24.02 72.74-51 6.47-12.51 9.77-24.61 13.68-38 .92-3.15 2.84-12.14 5.86-13.36 3.04-1.24 14.02 2.52 17.72 3.36-1.26 8.17-8.15 25.97-11.58 34-5.81 13.59-16.84 33.07-26.59 44-31.11 34.83-76.46 47.53-121.83 47l-10-.91c-51.9-3.79-98.9-34.39-122.25-81.09-7.95-15.91-13.72-35.09-13.75-53V344h-85v-21h84zm1033 278c3.78-3.96 6.56-11.85 8.86-17l10.14-19c14-24.5 31.19-47.55 54-64.52 23.86-17.76 53.23-27.43 83-27.48 39.69-.06 70.81 10.95 95.37 44 5.48 7.37 11.25 17.32 14.29 26 3.35 9.6 6.22 23.86 6.34 34v14c-.04 28.11-13.06 61.67-38 76.55-31.9 19.02-81.37 13.08-93.97-26.55-1.91-6.01-3-11.69-3.03-18-.06-12.34 1.28-21.95 7.31-33 10.92-20.01 27.32-28.32 21.67-54-.93-4.24-2.22-7.2-4.29-11-2.35-4.3-5.22-8.49-8.73-11.91-20.21-19.67-48.72-2.75-66.96 11.04-33.19 25.09-58.01 60.4-73.4 98.87-4.78 11.96-11.58 29.22-11.6 42v374h84v21h-283v-21h85V344h-85v-21h198zm-466.999-124.791-10.998.958-23.004 3.253c-21.64 3.91-43.02 10.712-63 19.892-79.69 36.58-140.437 107.547-164.417 191.686-5.63 19.75-10.343 43.482-10.583 64.002l-1.001 13 1 21.997c.29 24.06 9.88 62.344 18.42 85.004 19.16 50.79 56.6 100.81 99.58 133.77 14.999 11.5 31.134 21.04 48.004 29.48 12.1 6.05 27.106 12.72 39.996 16.73 20.769 6.46 41.401 9.628 63 11.108l10.004.91h7l9.998-.91c36.37-2.49 62.863-9.57 96.002-24.78 81.57-37.45 142.678-113.552 164.368-200.311 4.13-16.52 6.55-33.05 7.72-50L2411 608c.42-36.04-3.317-66.5-14.337-101-24.83-77.69-82.093-140.963-154.663-177.252-31.72-15.86-64.7-24.407-100-26.837l-10.998-.702zm-4.999 20.788c42.76-.5 77.78.522 112 30.292 45.279 39.38 56.67 105.944 62.17 162.713l1.831 31.995.995 14.001V639l-.995 15.003V658l-4.584 47.998c-.44 3.04-.568 15.981-6.158 12.921-3.07-1.68-5.392-12.287-6.592-15.917l-14.691-49-15.497-55.004c-.91-6.01 1.951-7.41 2.411-13 .74-8.78-4.653-10.067-5.933-14.997-.97-3.41 1.3-6.129 0-10.998-1.99-8.04-8.609-7.984-11.279-16.004l-21.032-83.996-5.768-25c-.58-2.46-2.468-9.874-1.978-11.994.71-3.06 3.895-5.127 6.085-7.177 6.75-6.31 20.68-24.232 4.01-28.302-2.34-.57-5.565-.569-7.995-.519-16.91.39-51.355 8.511-67.005 15.27-4.66 2.01-20.238 8.697-16.918 15.577 3.049 6.32 18.45 2.634 23.92 1.624 2.05-.49 7.461-2.08 8.831 0 1.47 2.42-2.301 4.2-3.851 4.9l-19.977 6.946c-23.37 7.79-39.702 11.472-64.002 14.942-5.43.77-19.622 2.937-23.382-1.703-3.13-3.85 1.739-8.855 4.419-11.395 7.37-6.98 20.021-14.473 28.961-19.592 27.07-15.49 71.973-28.331 103.003-32.581l26-3.168c2.42-.27 7.718-.92 8.228-3.93.69-4.13-5.567-4.73-8.227-4.92l-12-.94L2172 369l-39.001 4.577c-35.39 5.49-61.646 12.513-94.996 25.623l-30.004 13.049-19.995 9.753c2.36-10.35 8.464-22.77 13.714-32 19.9-34.99 47.85-56.242 87.28-64.002 6.3-1.24 17.745-2.923 24.005-3.003m66.999 111.005 15.716 51 17.81 62.995-2.136 18.005 5.847 10.999 1.215 13.989 10.107 13.013 4.321 16.998 9.998 39.996 13.12 56.006c-4.42 1.24-7.839 1.686-10.199-3.064l-8.862-26.94c-4.25-11.09-11.823-23.686-19.153-32.996-12.23-15.53-29.859-25.666-45.788-37.006-7.43-5.29-19.168-12.726-22.858-20.996-2.97-5.82-1.71-11.148 0-16.998l14.002-30.005c4.8-10.78 10.145-21.466 13.195-32.996 3.77-16.43 2.57-32.475 0-49.005l-2.935-19c-.47-2.34-1.603-6.589-.763-8.789 1.12-2.95 4.67-4.206 7.36-5.206m-22.004 12 5.573 28.997c2.14 12.77 2.431 30.5-.989 43-5 18.26-12.971 31.033-19.781 48.003-3.47 8.64-7.428 19.588-5.268 28.998 2.11 9.22 9.398 15.95 16.468 21.6l38 28.693c25.45 22.13 29.34 42.095 38.14 72.705 2.27 7.89 7.821 21.254 4.871 29.004-6.07 15.94-29.993 27.39-45.013 33.19-10.81 4.17-31.45 8.668-43 8.808-11.84.13-30.64-.918-39.66-9.528-4.78-4.56-6.49-16.934-7.99-23.474-2.839-12.36-9.29-34.326-9.35-45.996v-14.001c.08-17.52 12.591-42.553 19.861-59.003 3.76-8.51 8.07-17.596 8.82-26.996.92-11.62-8.261-21.642-16.681-28.332l-31-23.321c-5.99-4.62-12.548-9.18-16.998-15.35 8.98 1.69 10.744 2.037 18 2.001 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834l-3.205-13.977c-.71-4.81 2.182-5.25 6.202-5.89l22.998-3.73c21.53-4.31 43.191-9.32 64.001-16.4zm-183.996 33.996c1.86.62 3.778 1.053 5.158 2.563 1.52 1.66 3.069 7.106 3.839 9.436l6.67 22.003 15.754 53.998 9.119 33.002c1.47 8.66-3.763 10.57-2.143 17.999 1.1 5.11 4.89 7.409 5.92 10.999s-1.79 8.221 1.13 14.001c2.93 5.78 7.054 5.671 9.424 11.041l6.5 23.963 12 48.998 7.28 31 3.205 15.96c-.04 4.78-4.758 7.836-7.818 11.036-4.05 4.24-8.918 11.024-9.668 17.004-.76 5.99 3.19 11.086 7.63 14.606 7.41 5.88 24.562 9.283 34.002 9.393H2086l8.002.678 10.999-.678 25-1.849c30.48-3.64 61.102-11.558 90.002-21.838L2264.998 784c-2.02 7.1-7.028 16.508-10.718 22.998-17.27 30.37-42.621 50.971-76.281 60.571-12.31 3.52-24.33 4.648-37 5.518l-9.997.91h-6l-10.004-1.038h-7.995c-34.71-3.44-66.664-17.068-89.704-43.958-18.71-21.83-30.26-51.364-37.17-79.003C1967 697.479 1965.92 642.81 1966 589l1.001-16.998v-24.005l1.91-27.997c.68-9.68 2.451-31.382 5.091-40.002m31.159 2.081c1.73.025 3.339.579 4.419 2.234l9.112 26.685c3.71 10.18 11.637 23.47 18.317 32 11.96 15.25 31.032 27.111 46.99 38.281 7.5 5.25 18.965 12.212 22.645 20.722 4.83 11.2-5.614 28.711-10.334 39.001l-15.869 35.999c-4.43 14.65-4.457 24.091-4.437 39.001.02 9.82 2.186 19.458 4.346 28.998.58 2.55 3.004 12.998 2.594 14.898-.71 3.33-4.12 4.273-6.94 5.103L2056.289 701l-13.727-49c-.96-6.42 4.31-9.718 2.46-16.998-1.33-5.25-5.092-7.174-5.982-11.004-.93-3.95 2.541-7.606-1.129-13.996-3.41-5.95-7.6-5.524-9.93-12.023l-13.63-53.98-14.349-60.998c1.575-.445 3.426-.947 5.158-.922" data-color="1" fill="#000000"></path>
<path d="M3517.98 135.107c-3.32-.33-6.848.145-8.838 3.125l-4.81 13.77-9.002 26L3463.69 268l-18.11 53.003-10.919 32-35.003 101.996-63.318 182L3301.69 738l-25 72.003-8.88 26.001-6.482 18.994c-1.12 3.25-2.348 7.002-5.518 8.832-2.41 1.39-6.067 1.172-8.807 1.172h-56.006v21.002H3368V865h-89.002l37.665-107 7-20.002c1.46-4.2 2.465-8.731 6.385-11.401 2.73-1.86 5.814-1.59 8.954-1.6h252.001c3.27.01 7.02-.29 9.79 1.74 3.07 2.25 4.366 6.79 5.536 10.26L3613.33 758l35.669 107h-76.996v21.003h258.996V865H3777c-3.23-.01-7.047.29-9.777-1.74-2.94-2.19-4.105-6.89-5.225-10.26l-7-22.003L3718.328 721l-52.655-158.002-20.331-59.997L3605.327 382l-24.518-72.998L3566.998 268l-30.328-92-10.34-31c-1.64-4.87-2.439-9.304-8.349-9.894M3471.001 306l8.277 27.002 21.38 68L3561.022 594l21.997 70L3595 703.002h-259.002L3363.33 621l62.34-184.002L3444 383l14.19-41.998zM2173 744c3.71-5.26 14.86-6.15 21-5.98 2.88.07 8.51.59 6.83 5.01-1.54 4.06-9.01 7.42-12.83 9.11-12.82 5.67-29.08 8.99-43 10.57-5.45.63-17.42-.52-15.31-8.71 1.61-6.22 10.94-11.05 16.31-13.75 16.67-8.39 29.76-10.65 48-12.42 3.49-.34 5.21-.91 9-.79 7.22.23 23.7 1.98 24.84 10.96 1.1 8.67-9.58 17.08-15.84 21.57-19.44 13.96-45.45 20.34-69 22.11-3.24.24-4.89-.37-8-.59-9.29-.68-24.27-2.1-24.96-14.09-.56-9.79 5.68-23.95 9.54-33 5.81-13.61 11.11-27.58 14.54-42 2.63-11.11 2.9-18.75 2.88-30-.01-6.69-.29-6.63-1.04-13-.32-1.76-1.03-4.86 0-6.38 3.7-4.84 5.77 4.4 5.97 6.38l1.07 30c-.19 16.23-6.73 37.77-12.42 53-2.06 5.5-9.07 21.99-8.27 27 1.32 8.25 10.1 8.99 16.69 9 20.09.03 40.08-4.47 58-13.78 4.81-2.5 9.17-5.19 12.89-9.2 1.23-1.32 3.16-3.12 2.15-5.09-2.32-4.52-14.55-5.15-19.04-4.84-11.3.77-24.41 4.28-35 8.23-6.81 2.54-12.49 4.73-17 10.68 12.6 3.06 38.81-4.65 50-11-6.98.57-11.06 2.95-18 1m-119-201.002c8.98 1.69 10.744 2.038 18 2.002 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834 4.987 19.762 10.576 32.92 21.997 44" data-color="2" fill="#d40000"></path>
</g>
</svg>
</span></span></span></a>

In [ ]:
bs.find_all("a")

[<a aria-label="Historia.ID" class="WZxFET comp-mnpnfj6h_r_comp-ml93qt6j3-styleId__root wixui-button OOhWpA" data-testid="linkElement" href="https://www.historia.id" target="_self"><span class="UPWJFm"><span class="QeinDR wixui-button__label" data-testid="stylablebutton-label">Go</span><span aria-hidden="true" class="vwUNxR wixui-button__icon" data-testid="stylablebutton-icon"><span>
 <svg data-bbox="110 133.355 3720.999 766.645" data-type="color" height="330.881" viewbox="0 0 3941 1034" width="1261.123" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M110 323h283v21h-85v240h245V344h-85v-21h283v21h-84v521h85v21H468v-20h85V606H308v259h85v21H110v-20h84V344h-84Zm813-189.56c4.75-.38 15.2.91 20 1.98 51.24 11.48 69.64 76.52 34.83 114.57C967.2 261.6 947.87 270.81 932 271h-12c-7.52-.09-15.02-2.09-22-4.81-37.08-14.48-52.07-57.93-35.51-93.19 9.46-20.14 27.91-33.91 49.51-38.33ZM784 323h198v542h85v21H784v-21h85V344h-85zm317 445h30c2.13 0 5.58-.25 7.37.99 1.73 1.22 3.4 5.07 4.39 7.01l7.44 13c9.18 15.11 27.56 38.35 40.8 49.7 51.55 44.18 143.12 61.05 192.95 5.3 7.28-8.15 12.16-16.82 15.99-27 3.55-9.45 6.04-25.87 6.06-36v-14c-.02-11.2-2.66-20.61-6.58-31-8.78-23.27-21.59-40.05-43.42-52.72-25.96-15.05-51.74-21.52-80-30.3-23.66-7.36-49.45-16.51-72-26.68-25.36-11.43-46.85-23.05-64.55-45.3-18.81-23.64-26.67-53.48-29.62-83l-.83-9c-.19-16.73-.37-28.29 2.43-45 7.03-41.87 26.54-74.74 59.57-101.54 16.49-13.38 36.01-21.79 56-28.46 15.9-5.3 34.16-9.97 51-10h20c17.02.2 40.18 5.33 56 11.6 10.7 4.25 28.08 13.79 39 13.36 10.5-.41 17.24-4.91 24-6.43 3.71-.84 14.58-.53 19-.53v147h-16c-.93-11.4-6.88-30.07-10.95-41-14.75-39.58-42.69-84.56-85.05-97.97-12.37-3.92-33.91-6.05-47-6.03-46.2.07-95.06 27.07-110.66 72-2.86 8.26-5.23 17.2-5.34 26-.3 25.66 9.93 53.68 31 69.49 9.32 6.99 37.97 18.8 50 23.93 68.31 29.14 159 45.27 211.99 99.58 11.73 12.03 21.95 28.41 28.21 44 8.54 21.28 11.06 44.22 10.8 67l-.91 10c-5.38 73.56-61.07 131.31-129.09 154-15.45 5.15-36.74 9.97-53 10h-23c-24.3-.04-51.1-8.03-74-15.67l-42-14.66c-7.19-2.35-19.59-6-27-5.58-6.93.4-14.46 1.84-19.98 6.3-5.09 4.1-5.61 7.74-8.41 9.04-1.99.92-11.82.57-14.61.57zm1908-634.56c5.68-.45 15.41.97 21 2.44 44.02 11.61 65.19 64.28 41.54 103.12-11.4 18.71-33.5 31.9-55.54 32h-11c-7.22-.09-14.33-1.91-21-4.6-38.28-15.46-53.35-58.99-35.03-95.4 8.05-16.01 22.95-28.8 40.03-34.25 8.24-2.64 12.1-2.24 20-3.31M2875 323h198v542h86v21h-284v-21h85V344h-85zM1552 149c5.57 1.04 10.66 3.8 16 5.66 10.74 3.72 23.58 7.2 35 7.34 13.63.16 27.44-2.49 40-7.87l23-11.13v180h170v21h-170v433l.91 10c2.15 30.67 10.55 64.42 41.09 78.68 11.84 5.53 28.02 7.47 41 7.32 31.54-.37 58.79-24.02 72.74-51 6.47-12.51 9.77-24.61 13.68-38 .92-3.15 2.84-12.14 5.86-13.36 3.04-1.24 14.02 2.52 17.72 3.36-1.26 8.17-8.15 25.97-11.58 34-5.81 13.59-16.84 33.07-26.59 44-31.11 34.83-76.46 47.53-121.83 47l-10-.91c-51.9-3.79-98.9-34.39-122.25-81.09-7.95-15.91-13.72-35.09-13.75-53V344h-85v-21h84zm1033 278c3.78-3.96 6.56-11.85 8.86-17l10.14-19c14-24.5 31.19-47.55 54-64.52 23.86-17.76 53.23-27.43 83-27.48 39.69-.06 70.81 10.95 95.37 44 5.48 7.37 11.25 17.32 14.29 26 3.35 9.6 6.22 23.86 6.34 34v14c-.04 28.11-13.06 61.67-38 76.55-31.9 19.02-81.37 13.08-93.97-26.55-1.91-6.01-3-11.69-3.03-18-.06-12.34 1.28-21.95 7.31-33 10.92-20.01 27.32-28.32 21.67-54-.93-4.24-2.22-7.2-4.29-11-2.35-4.3-5.22-8.49-8.73-11.91-20.21-19.67-48.72-2.75-66.96 11.04-33.19 25.09-58.01 60.4-73.4 98.87-4.78 11.96-11.58 29.22-11.6 42v374h84v21h-283v-21h85V344h-85v-21h198zm-466.999-124.791-10.998.958-23.004 3.253c-21.64 3.91-43.02 10.712-63 19.892-79.69 36.58-140.437 107.547-164.417 191.686-5.63 19.75-10.343 43.482-10.583 64.002l-1.001 13 1 21.997c.29 24.06 9.88 62.344 18.42 85.004 19.16 50.79 56.6 100.81 99.58 133.77 14.999 11.5 31.134 21.04 48.004 29.48 12.1 6.05 27.106 12.72 39.996 16.73 20.769 6.46 41.401 9.628 63 11.108l10.004.91h7l9.998-.91c36.37-2.49 62.863-9.57 96.002-24.78 81.57-37.45 142.678-113.552 164.368-200.311 4.13-16.52 6.55-33.05 7.72-50L2411 608c.42-36.04-3.317-66.5-14.337-101-24.83-77.69-82.093-140.963-154.663-177.252-31.72-15.86-64.7-24.407-100-26.837l-10.998-.702zm-4.999 20.788c42.76-.5 77.78.522 112 30.292 45.279 39.38 56.67 105.944 62.17 162.713l1.831 31.995.995 14.001V639l-.995 15.003V658l-4.584 47.998c-.44 3.04-.568 15.981-6.158 12.921-3.07-1.68-5.392-12.287-6.592-15.917l-14.691-49-15.497-55.004c-.91-6.01 1.951-7.41 2.411-13 .74-8.78-4.653-10.067-5.933-14.997-.97-3.41 1.3-6.129 0-10.998-1.99-8.04-8.609-7.984-11.279-16.004l-21.032-83.996-5.768-25c-.58-2.46-2.468-9.874-1.978-11.994.71-3.06 3.895-5.127 6.085-7.177 6.75-6.31 20.68-24.232 4.01-28.302-2.34-.57-5.565-.569-7.995-.519-16.91.39-51.355 8.511-67.005 15.27-4.66 2.01-20.238 8.697-16.918 15.577 3.049 6.32 18.45 2.634 23.92 1.624 2.05-.49 7.461-2.08 8.831 0 1.47 2.42-2.301 4.2-3.851 4.9l-19.977 6.946c-23.37 7.79-39.702 11.472-64.002 14.942-5.43.77-19.622 2.937-23.382-1.703-3.13-3.85 1.739-8.855 4.419-11.395 7.37-6.98 20.021-14.473 28.961-19.592 27.07-15.49 71.973-28.331 103.003-32.581l26-3.168c2.42-.27 7.718-.92 8.228-3.93.69-4.13-5.567-4.73-8.227-4.92l-12-.94L2172 369l-39.001 4.577c-35.39 5.49-61.646 12.513-94.996 25.623l-30.004 13.049-19.995 9.753c2.36-10.35 8.464-22.77 13.714-32 19.9-34.99 47.85-56.242 87.28-64.002 6.3-1.24 17.745-2.923 24.005-3.003m66.999 111.005 15.716 51 17.81 62.995-2.136 18.005 5.847 10.999 1.215 13.989 10.107 13.013 4.321 16.998 9.998 39.996 13.12 56.006c-4.42 1.24-7.839 1.686-10.199-3.064l-8.862-26.94c-4.25-11.09-11.823-23.686-19.153-32.996-12.23-15.53-29.859-25.666-45.788-37.006-7.43-5.29-19.168-12.726-22.858-20.996-2.97-5.82-1.71-11.148 0-16.998l14.002-30.005c4.8-10.78 10.145-21.466 13.195-32.996 3.77-16.43 2.57-32.475 0-49.005l-2.935-19c-.47-2.34-1.603-6.589-.763-8.789 1.12-2.95 4.67-4.206 7.36-5.206m-22.004 12 5.573 28.997c2.14 12.77 2.431 30.5-.989 43-5 18.26-12.971 31.033-19.781 48.003-3.47 8.64-7.428 19.588-5.268 28.998 2.11 9.22 9.398 15.95 16.468 21.6l38 28.693c25.45 22.13 29.34 42.095 38.14 72.705 2.27 7.89 7.821 21.254 4.871 29.004-6.07 15.94-29.993 27.39-45.013 33.19-10.81 4.17-31.45 8.668-43 8.808-11.84.13-30.64-.918-39.66-9.528-4.78-4.56-6.49-16.934-7.99-23.474-2.839-12.36-9.29-34.326-9.35-45.996v-14.001c.08-17.52 12.591-42.553 19.861-59.003 3.76-8.51 8.07-17.596 8.82-26.996.92-11.62-8.261-21.642-16.681-28.332l-31-23.321c-5.99-4.62-12.548-9.18-16.998-15.35 8.98 1.69 10.744 2.037 18 2.001 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834l-3.205-13.977c-.71-4.81 2.182-5.25 6.202-5.89l22.998-3.73c21.53-4.31 43.191-9.32 64.001-16.4zm-183.996 33.996c1.86.62 3.778 1.053 5.158 2.563 1.52 1.66 3.069 7.106 3.839 9.436l6.67 22.003 15.754 53.998 9.119 33.002c1.47 8.66-3.763 10.57-2.143 17.999 1.1 5.11 4.89 7.409 5.92 10.999s-1.79 8.221 1.13 14.001c2.93 5.78 7.054 5.671 9.424 11.041l6.5 23.963 12 48.998 7.28 31 3.205 15.96c-.04 4.78-4.758 7.836-7.818 11.036-4.05 4.24-8.918 11.024-9.668 17.004-.76 5.99 3.19 11.086 7.63 14.606 7.41 5.88 24.562 9.283 34.002 9.393H2086l8.002.678 10.999-.678 25-1.849c30.48-3.64 61.102-11.558 90.002-21.838L2264.998 784c-2.02 7.1-7.028 16.508-10.718 22.998-17.27 30.37-42.621 50.971-76.281 60.571-12.31 3.52-24.33 4.648-37 5.518l-9.997.91h-6l-10.004-1.038h-7.995c-34.71-3.44-66.664-17.068-89.704-43.958-18.71-21.83-30.26-51.364-37.17-79.003C1967 697.479 1965.92 642.81 1966 589l1.001-16.998v-24.005l1.91-27.997c.68-9.68 2.451-31.382 5.091-40.002m31.159 2.081c1.73.025 3.339.579 4.419 2.234l9.112 26.685c3.71 10.18 11.637 23.47 18.317 32 11.96 15.25 31.032 27.111 46.99 38.281 7.5 5.25 18.965 12.212 22.645 20.722 4.83 11.2-5.614 28.711-10.334 39.001l-15.869 35.999c-4.43 14.65-4.457 24.091-4.437 39.001.02 9.82 2.186 19.458 4.346 28.998.58 2.55 3.004 12.998 2.594 14.898-.71 3.33-4.12 4.273-6.94 5.103L2056.289 701l-13.727-49c-.96-6.42 4.31-9.718 2.46-16.998-1.33-5.25-5.092-7.174-5.982-11.004-.93-3.95 2.541-7.606-1.129-13.996-3.41-5.95-7.6-5.524-9.93-12.023l-13.63-53.98-14.349-60.998c1.575-.445 3.426-.947 5.158-.922" data-color="1" fill="#000000"></path>
 <path d="M3517.98 135.107c-3.32-.33-6.848.145-8.838 3.125l-4.81 13.77-9.002 26L3463.69 268l-18.11 53.003-10.919 32-35.003 101.996-63.318 182L3301.69 738l-25 72.003-8.88 26.001-6.482 18.994c-1.12 3.25-2.348 7.002-5.518 8.832-2.41 1.39-6.067 1.172-8.807 1.172h-56.006v21.002H3368V865h-89.002l37.665-107 7-20.002c1.46-4.2 2.465-8.731 6.385-11.401 2.73-1.86 5.814-1.59 8.954-1.6h252.001c3.27.01 7.02-.29 9.79 1.74 3.07 2.25 4.366 6.79 5.536 10.26L3613.33 758l35.669 107h-76.996v21.003h258.996V865H3777c-3.23-.01-7.047.29-9.777-1.74-2.94-2.19-4.105-6.89-5.225-10.26l-7-22.003L3718.328 721l-52.655-158.002-20.331-59.997L3605.327 382l-24.518-72.998L3566.998 268l-30.328-92-10.34-31c-1.64-4.87-2.439-9.304-8.349-9.894M3471.001 306l8.277 27.002 21.38 68L3561.022 594l21.997 70L3595 703.002h-259.002L3363.33 621l62.34-184.002L3444 383l14.19-41.998zM2173 744c3.71-5.26 14.86-6.15 21-5.98 2.88.07 8.51.59 6.83 5.01-1.54 4.06-9.01 7.42-12.83 9.11-12.82 5.67-29.08 8.99-43 10.57-5.45.63-17.42-.52-15.31-8.71 1.61-6.22 10.94-11.05 16.31-13.75 16.67-8.39 29.76-10.65 48-12.42 3.49-.34 5.21-.91 9-.79 7.22.23 23.7 1.98 24.84 10.96 1.1 8.67-9.58 17.08-15.84 21.57-19.44 13.96-45.45 20.34-69 22.11-3.24.24-4.89-.37-8-.59-9.29-.68-24.27-2.1-24.96-14.09-.56-9.79 5.68-23.95 9.54-33 5.81-13.61 11.11-27.58 14.54-42 2.63-11.11 2.9-18.75 2.88-30-.01-6.69-.29-6.63-1.04-13-.32-1.76-1.03-4.86 0-6.38 3.7-4.84 5.77 4.4 5.97 6.38l1.07 30c-.19 16.23-6.73 37.77-12.42 53-2.06 5.5-9.07 21.99-8.27 27 1.32 8.25 10.1 8.99 16.69 9 20.09.03 40.08-4.47 58-13.78 4.81-2.5 9.17-5.19 12.89-9.2 1.23-1.32 3.16-3.12 2.15-5.09-2.32-4.52-14.55-5.15-19.04-4.84-11.3.77-24.41 4.28-35 8.23-6.81 2.54-12.49 4.73-17 10.68 12.6 3.06 38.81-4.65 50-11-6.98.57-11.06 2.95-18 1m-119-201.002c8.98 1.69 10.744 2.038 18 2.002 18.939-.22 44.353-7.35 60.003-18.03 8.87-6.05 19.545-15.88 23.645-25.97 4.42-10.89-2.868-17.573-13.648-16.913-15.15.93-25.042 11.221-33.002 14.911l1.001 4.004c7.87-3.84 14.94-9.742 24-10.822 3.89-.46 9.663-.51 9.643 4.84-.02 6.43-8.651 12.789-13.641 15.699-14.09 8.19-31.468 15.083-47.998 15.283-14 .16-25.322-2.24-35.962-12.17-3.91-3.65-10.728-15.674-14.038-16.834 4.987 19.762 10.576 32.92 21.997 44" data-color="2" fill="#d40000"></path>
 </g>
 </svg>
 </span></span></span></a>,
 <a aria-label="Politik" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/politik" id="comp-mnpnfj6h_r_comp-ml93qt6q__3f96b9a3-7759-4b82-a080-ca2f9b817145" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Politik</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Kultur" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/kultur" id="comp-mnpnfj6h_r_comp-ml93qt6q__af351648-85dc-449e-8e04-b95ead47d5e5" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Kultur</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Militer" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/militer" id="comp-mnpnfj6h_r_comp-ml93qt6q__b991a13e-dbae-42e3-ae8b-78dcc957f2fb" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Militer</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Ekonomi" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/ekonomi" id="comp-mnpnfj6h_r_comp-ml93qt6q__698ea6d3-3bc7-491d-8aaa-afcc6a0ff27f" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Ekonomi</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Olahraga" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/olahraga" id="comp-mnpnfj6h_r_comp-ml93qt6q__009620a2-2695-4a44-8f5a-920a2b2015cf" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Olahraga</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Sains" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/sains" id="comp-mnpnfj6h_r_comp-ml93qt6q__a3330096-f52d-4411-a191-89e227fba328" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Sains</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Urban" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6q comp-mnpnfj6h_r_comp-ml93qt6q-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/categories/urban" id="comp-mnpnfj6h_r_comp-ml93qt6q__5d7cf9ee-550d-436b-8620-f0d955d28897" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Urban</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Kerjasama &amp; Portofolio" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6t4 comp-mnpnfj6h_r_comp-ml93qt6t4-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/layanan-dan-portofolio" id="comp-mnpnfj6h_r_comp-ml93qt6t4__5f50c101-c1dd-48bc-a6ae-b6cd7741c161" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Kerjasama &amp; Portofolio</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Undangan Menulis" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6t4 comp-mnpnfj6h_r_comp-ml93qt6t4-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/page/undangan-menulis" id="comp-mnpnfj6h_r_comp-ml93qt6t4__af8ac034-df86-4541-84d8-dae78c22cb0a" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Undangan Menulis</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>
 <path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
 </g>
 </svg>
 </span></span></a>,
 <a aria-label="Premium" class="a_1__O KSh0Yl comp-mnpnfj6h_r_comp-ml93qt6t4 comp-mnpnfj6h_r_comp-ml93qt6t4-styleId__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/premium" id="comp-mnpnfj6h_r_comp-ml93qt6t4__a0d7ad13-12ed-41a5-bb02-644847d6cc1c" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Premium</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
 <g>

In [ ]:
[tag.text.strip() for tag in bs.find_all(['h1', 'h2', 'h3'])]

['Ikuti Kami',
 'TERPOPULER',
 'Istilah “Bersiap” yang Problematik',
 'Senjakala Semaoen',
 'Anjangsana Ahmad Subardjo di Negeri Persia',
 'Semaoen dan Sneevliet, Simbiosis Mutualisme Mentor dan Murid',
 'Ahmad Subardjo di Palestina',
 'Raden Ayu Pudji Astuti, Setia Mendampingi Ahmad Subardjo',
 'Potong Kuping Demi Indonesia Merdeka',
 'Jejak Multatuli Setelah Meninggalkan Lebak',
 'Pasang Badan Demi Proklamasi Kemerdekaan',
 'Riwayat Ayah dan Anak van Roijen',
 'Musisi Kulit Hitam Amerika Menyanyi Lagu Indonesia Raya',
 'Sjahrir dan Sukarno dalam Peringatan HUT RI Pertama',
 'Spirit Merah Putih Ahmad Subardjo di Negeri Belanda',
 'Kabar Angin Tan Malaka di Palestina',
 'Kabinet Bayangan Masa Orde Baru',
 'TERPOPULER',
 '1',
 '2',
 '3',
 'TRENDING',
 'TRENDING :']

In [ ]:
semua_judul = bs.find_all(['h2', 'h3'])

judul_artikel_pertama = None

for tag in semua_judul:
    teks = tag.text.strip()
    if teks not in ['Ikuti Kami', 'TERPOPULER', 'TRENDING', 'TRENDING :'] and not teks.isdigit():
        judul_artikel_pertama = tag
        break

if judul_artikel_pertama:
    print("Judul Artikel Pertama:", judul_artikel_pertama.text.strip())
else:
    print("Judul artikel tidak ditemukan.")

Judul Artikel Pertama: Istilah “Bersiap” yang Problematik

In [ ]:
semua_judul = bs.find_all(['h2', 'h3'])
daftar_judul = []

for tag in semua_judul:
    teks = tag.text.strip()
    if teks not in ['Ikuti Kami', 'TERPOPULER', 'TRENDING', 'TRENDING :'] and not teks.isdigit():
        daftar_judul.append(tag)

print(f"Ditemukan {len(daftar_judul)} judul artikel.")

Ditemukan 15 judul artikel.

In [ ]:
if daftar_judul:
    judul = daftar_judul[0]
    print("Judul Kategori:", judul.text.strip())

    link = judul.find_parent('a')
    if not link:
        link = judul.find('a')

    if link and 'href' in link.attrs:
        print("Link Halaman:", link['href'])
    else:
        print("Link halaman tidak ditemukan pada elemen ini.")
else:
    print("Daftar judul kosong.")

Judul Kategori: Istilah “Bersiap” yang Problematik
Link Halaman: https://www.historia.id/article/istilah-bersiap-yang-problematik-vogkk

In [ ]:
for judul in daftar_judul:
    print(judul.text.strip())

Istilah “Bersiap” yang Problematik
Senjakala Semaoen
Anjangsana Ahmad Subardjo di Negeri Persia
Semaoen dan Sneevliet, Simbiosis Mutualisme Mentor dan Murid
Ahmad Subardjo di Palestina
Raden Ayu Pudji Astuti, Setia Mendampingi Ahmad Subardjo
Potong Kuping Demi Indonesia Merdeka
Jejak Multatuli Setelah Meninggalkan Lebak
Pasang Badan Demi Proklamasi Kemerdekaan
Riwayat Ayah dan Anak van Roijen
Musisi Kulit Hitam Amerika Menyanyi Lagu Indonesia Raya
Sjahrir dan Sukarno dalam Peringatan HUT RI Pertama
Spirit Merah Putih Ahmad Subardjo di Negeri Belanda
Kabar Angin Tan Malaka di Palestina
Kabinet Bayangan Masa Orde Baru

In [ ]:
card = daftar_judul[0].parent.parent
for tag in card.find_all(['span', 'p', 'div']):
    teks = tag.text.strip()
    if teks and teks != daftar_judul[0].text.strip():
        print(f"Tag <{tag.name}>: {teks}")

In [ ]:
test_desc = bs.find_all('p', class_=lambda x: x and 'wixui-collapsible-text' in x)

print(f"Jumlah deskripsi yang ditemukan: {len(test_desc)}")
for d in test_desc[:5]:
    print("-", d.text.strip()[:100])

Jumlah deskripsi yang ditemukan: 4
- Kepulangan Semaoen ke Indonesia setelah 33 tahun di pengasingan disambut semarak. Presiden Soeharto
- Getol berorganisasi ketimbang kuliah, Ahmad Subardjo mengubah haluan Perhimpunan Indonesia. Menggaga
- Setelah diculik pengikut Tan Malaka, Sutan Sjahrir bikin perhitungan dengan penangkapan berantai. Ad
- Donald Trump menghina Paus Leo XIV. Dahulu Napoleon menangkap dua Bapa Suci.

In [ ]:
semua_desc = bs.find_all('p', class_=lambda x: x and 'wixui-collapsible-text' in x)

for i in range(len(daftar_judul)):
    judul_teks = daftar_judul[i].text.strip()

    if i < len(semua_desc):
        desc_text = semua_desc[i].text.strip()
        print(f"Judul: {judul_teks}")
        print(f"Deskripsi: {desc_text[:100]}...\n")
    else:
        print(f"Judul: {judul_teks}\nDeskripsi: -\n")

Judul: Istilah “Bersiap” yang Problematik
Deskripsi: Kepulangan Semaoen ke Indonesia setelah 33 tahun di pengasingan disambut semarak. Presiden Soeharto ...

Judul: Senjakala Semaoen
Deskripsi: Getol berorganisasi ketimbang kuliah, Ahmad Subardjo mengubah haluan Perhimpunan Indonesia. Menggaga...

Judul: Anjangsana Ahmad Subardjo di Negeri Persia
Deskripsi: Setelah diculik pengikut Tan Malaka, Sutan Sjahrir bikin perhitungan dengan penangkapan berantai. Ad...

Judul: Semaoen dan Sneevliet, Simbiosis Mutualisme Mentor dan Murid
Deskripsi: Donald Trump menghina Paus Leo XIV. Dahulu Napoleon menangkap dua Bapa Suci....

Judul: Ahmad Subardjo di Palestina
Deskripsi: -

Judul: Raden Ayu Pudji Astuti, Setia Mendampingi Ahmad Subardjo
Deskripsi: -

Judul: Potong Kuping Demi Indonesia Merdeka
Deskripsi: -

Judul: Jejak Multatuli Setelah Meninggalkan Lebak
Deskripsi: -

Judul: Pasang Badan Demi Proklamasi Kemerdekaan
Deskripsi: -

Judul: Riwayat Ayah dan Anak van Roijen
Deskripsi: -

Judul: Musisi Kulit Hitam Amerika Menyanyi Lagu Indonesia Raya
Deskripsi: -

Judul: Sjahrir dan Sukarno dalam Peringatan HUT RI Pertama
Deskripsi: -

Judul: Spirit Merah Putih Ahmad Subardjo di Negeri Belanda
Deskripsi: -

Judul: Kabar Angin Tan Malaka di Palestina
Deskripsi: -

Judul: Kabinet Bayangan Masa Orde Baru
Deskripsi: -

**Scraping banyak pages**

In [ ]:
import cloudscraper
from bs4 import BeautifulSoup
import time

root = 'https://www.historia.id/articles/categories/politik/page/'
scraper = cloudscraper.create_scraper(browser={'browser': 'chrome', 'platform': 'windows', 'mobile': False})

kategori_judul = []
links = []
penjelasan = []

for page in range(1, 6):
    print(f"Mengambil data dari Halaman {page}...")

    url = root + str(page)
    response = scraper.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        semua_judul_mentah = soup.find_all(['h2', 'h3'])
        judul_valid = [tag for tag in semua_judul_mentah
                       if tag.text.strip() not in ['Ikuti Kami', 'TERPOPULER', 'TRENDING', 'TRENDING :']
                       and not tag.text.strip().isdigit()
                       and tag.text.strip() != ""]

        semua_desc = soup.find_all('p', class_=lambda x: x and 'wixui-collapsible-text' in x)

        for i, tag_judul in enumerate(judul_valid):
            teks_judul = tag_judul.text.strip()

            kategori_judul.append(teks_judul)

            link_tag = tag_judul.find_parent('a') or tag_judul.find('a')
            if link_tag and 'href' in link_tag.attrs:
                href = link_tag['href']
                full_url = href if href.startswith('http') else 'https://www.historia.id' + href
                links.append(full_url)
            else:
                links.append("-")

            if i < len(semua_desc):
                penjelasan.append(semua_desc[i].text.strip())
            else:
                penjelasan.append("-")

    else:
        print(f"Gagal mengakses halaman {page}. Status Code: {response.status_code}")

    time.sleep(2)

print("Scraping donee")
print(f"   Halaman {page}: {len(judul_valid)} judul, {len(semua_desc)} deskripsi ditemukan")

Mengambil data dari Halaman 1...
Mengambil data dari Halaman 2...
Mengambil data dari Halaman 3...
Mengambil data dari Halaman 4...
Mengambil data dari Halaman 5...
Scraping donee
   Halaman 5: 15 judul, 4 deskripsi ditemukan

In [ ]:
len(kategori_judul), len(links), len(penjelasan)

(75, 75, 75)

In [ ]:
import pandas as pd
df = pd.DataFrame({'Judul Artikel': kategori_judul,
                   'Link Halaman': links,
                   'Penjelasan': penjelasan})
df

,Judul Artikel,Link Halaman,Penjelasan
0,Istilah “Bersiap” yang Problematik,https://www.historia.id/article/istilah-bersia...,Kepulangan Semaoen ke Indonesia setelah 33 tah...
1,Senjakala Semaoen,https://www.historia.id/article/senjakala-semaoen,"Getol berorganisasi ketimbang kuliah, Ahmad Su..."
2,Anjangsana Ahmad Subardjo di Negeri Persia,https://www.historia.id/article/anjangsana-ahm...,"Setelah diculik pengikut Tan Malaka, Sutan Sja..."
3,"Semaoen dan Sneevliet, Simbiosis Mutualisme Me...",https://www.historia.id/article/semaoen-dan-sn...,Donald Trump menghina Paus Leo XIV. Dahulu Nap...
4,Ahmad Subardjo di Palestina,https://www.historia.id/article/ahmad-subardjo...,-
...,...,...,...
70,Akhir Perlawanan Tuan Rondahaim Terhadap Belanda,https://www.historia.id/article/akhir-perlawan...,-
71,Persekutuan Tuan Rondahaim dan Sisingamangaraja,https://www.historia.id/article/persekutuan-tu...,-
72,Wanita Perkasa Pembela Jelata,https://www.historia.id/article/wanita-perkasa...,-
73,Prajurit Keraton Ikut PKI,https://www.historia.id/article/prajurit-kerat...,-
74,Perang Jawa Memicu Kemerdekaan Belgia dari Bel...,https://www.historia.id/article/perang-jawa-me...,-

In [ ]:
print(tag_judul.parent.parent.parent.parent)

<div class="HFEOE3 NaeT1r comp-mnpplh9k wixui-box" dir="ltr" id="comp-mnpplh9k" role=""><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-box"></div><div class="comp-mnpplh9k-overflow-wrapper ku1hVK" data-testid="responsive-container-overflow"><div class="comp-mnpplh9k-container" data-testid="responsive-container-content" role="group" tabindex="-1"><!--$--><div class="N8MGzv _v6ohL AWXfZq PO9MfV comp-mnpplh9m1 wixui-rich-text" data-testid="richTextElement" id="comp-mnpplh9m1"><h2 class="font_2 wixui-rich-text__text">TRENDING : </h2></div><!--/$--><!--$--><div class="ArRNfA comp-mnpplh9o4 wixui-repeater" id="comp-mnpplh9o4"><div class="comp-mnpplh9o4-overflow-wrapper ku1hVK" data-testid="responsive-container-overflow"><div class="comp-mnpplh9o4-container" data-testid="responsive-container-content" role="list" tabindex="-1"><!--$--><div class="HFEOE3 NaeT1r comp-mnpplh9q-container comp-mnpplh9q wixui-repeater__item" dir="ltr" id="comp-mnpplh9q__2e67499e-bc82-42eb-8f2b-c779de88b1f0" role="listitem"><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-repeater__item"></div><!--$--><a aria-label="Kolonialisme" class="a_1__O KSh0Yl comp-mnpplh9r style-mnpplh9s3__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/tags/kolonialisme" id="comp-mnpplh9r__2e67499e-bc82-42eb-8f2b-c779de88b1f0" rel="noopener noreferrer" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Kolonialisme</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
</g>
</svg>
</span></span></a><!--/$--></div><!--/$--><!--$--><div class="HFEOE3 NaeT1r comp-mnpplh9q-container comp-mnpplh9q wixui-repeater__item" dir="ltr" id="comp-mnpplh9q__8421a763-aa0f-4252-9ff1-517a7dbda063" role="listitem"><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-repeater__item"></div><!--$--><a aria-label="Pertambangan" class="a_1__O KSh0Yl comp-mnpplh9r style-mnpplh9s3__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/tags/pertambangan" id="comp-mnpplh9r__8421a763-aa0f-4252-9ff1-517a7dbda063" rel="noopener noreferrer" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Pertambangan</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
</g>
</svg>
</span></span></a><!--/$--></div><!--/$--><!--$--><div class="HFEOE3 NaeT1r comp-mnpplh9q-container comp-mnpplh9q wixui-repeater__item" dir="ltr" id="comp-mnpplh9q__f3fdf328-2935-4f0e-8d5b-bd38520661d2" role="listitem"><div aria-hidden="true" class="jdJeEr NYfD3h inner-box wixui-repeater__item"></div><!--$--><a aria-label="Sukarno" class="a_1__O KSh0Yl comp-mnpplh9r style-mnpplh9s3__root wixui-button mfEw8N" data-semantic-classname="button" data-testid="buttonContent" dir="inherit" href="https://www.historia.id/articles/tags/sukarno" id="comp-mnpplh9r__f3fdf328-2935-4f0e-8d5b-bd38520661d2" rel="noopener noreferrer" target="_self"><span class="nb2UT3 GxMh7V wixui-button__label" data-testid="stylablebutton-label">Sukarno</span><span aria-hidden="true" class="KoOUdA mdITnz wixui-button__icon" data-testid="stylablebutton-icon"><span><svg data-bbox="20 20 160 160" data-type="shape" height="200" viewbox="0 0 200 200" width="200" xmlns="http://www.w3.org/2000/svg">
<g>
<path d="M100 20c-44.184 0-80 35.817-80 80.001C20 144.183 55.817 180 100 180s80-35.817 80-79.999S144.183 20 100 20zm-9.999 126.345l-10.997-10.998 35.346-35.346-35.346-35.347 10.997-10.998L136.345 100l-46.344 46.345z"></path>
</g>
</svg>
</span></span></a><!--/$--></div><!--/$--></div></div></div><!--/$--></div></div></div>

In [ ]:
# Berikut untuk untuk deskripsi yang konsisten dan lebih informatif dengan menggunakan <meta name="description">

import time

deskripsi_lengkap = []

for i, link in enumerate(links):
    if link == "-":
        deskripsi_lengkap.append("-")
        continue

    try:
        resp = scraper.get(link)
        if resp.status_code == 200:
            soup_artikel = BeautifulSoup(resp.text, 'html.parser')

            meta_desc = soup_artikel.find('meta', attrs={'name': 'description'})
            if not meta_desc or not meta_desc.get('content'):
                meta_desc = soup_artikel.find('meta', attrs={'property': 'og:description'})

            if meta_desc and meta_desc.get('content'):
                deskripsi_lengkap.append(meta_desc['content'].strip())
            else:
                deskripsi_lengkap.append("-")
        else:
            deskripsi_lengkap.append("-")
    except Exception as e:
        deskripsi_lengkap.append("-")

    print(f"{i+1}/{len(links)} selesai: {kategori_judul[i][:50]}")
    time.sleep(1.5)

df['Penjelasan'] = deskripsi_lengkap
df

1/75 selesai: Istilah “Bersiap” yang Problematik
2/75 selesai: Senjakala Semaoen
3/75 selesai: Anjangsana Ahmad Subardjo di Negeri Persia
4/75 selesai: Semaoen dan Sneevliet, Simbiosis Mutualisme Mentor
5/75 selesai: Ahmad Subardjo di Palestina
6/75 selesai: Raden Ayu Pudji Astuti, Setia Mendampingi Ahmad Su
7/75 selesai: Potong Kuping Demi Indonesia Merdeka
8/75 selesai: Jejak Multatuli Setelah Meninggalkan Lebak
9/75 selesai: Pasang Badan Demi Proklamasi Kemerdekaan
10/75 selesai: Riwayat Ayah dan Anak van Roijen
11/75 selesai: Musisi Kulit Hitam Amerika Menyanyi Lagu Indonesia
12/75 selesai: Sjahrir dan Sukarno dalam Peringatan HUT RI Pertam
13/75 selesai: Spirit Merah Putih Ahmad Subardjo di Negeri Beland
14/75 selesai: Kabar Angin Tan Malaka di Palestina
15/75 selesai: Kabinet Bayangan Masa Orde Baru
16/75 selesai: Kabinet Bayangan Tan Malaka
17/75 selesai: Dari Srebrenica ke Palestina
18/75 selesai: Buru Sergap Pendukung Tan Malaka Imbas Penculikan
19/75 selesai: Suka Duka Siti Djauhari Sudiro
20/75 selesai: Langkah Kaki Sudiro di Parlemen
21/75 selesai: Sudiro Muda Antara Belajar, Berorganisasi, dan Ber
22/75 selesai: Kisah Horor Tambang Batubara Loa Kulu
23/75 selesai: 28 Mei 1738: Joseph-Ignace Guillotin Lahir
24/75 selesai: Pekik Merdeka Shamsiah Fakeh (Bagian III)
25/75 selesai: Horison Terbit di Awal Orde Baru
26/75 selesai: Sutan Sjahrir Memodali Chairil Anwar Jualan Barang
27/75 selesai: Ayah Chairil Anwar Dieksekusi Tentara Belanda dala
28/75 selesai: Pekik Merdeka Shamsiah Fakeh (Bagian II)
29/75 selesai: Lika-liku Perjuangan Marwan Barghouti
30/75 selesai: Gereja Katolik dan Pemimpin Agresor
31/75 selesai: Larangan Perayaan Ulang Tahun Pejabat Orde Baru
32/75 selesai: 21 April 1619: Pejabat VOC yang Mendirikan Cape To
33/75 selesai: Memantik Global Selatan Melawan Kolonialitas
34/75 selesai: K’tut Tantri Penyintas Kamp Interniran Jepang
35/75 selesai: Gouw Ji Lu Luput dari Pembantaian Tangerang
36/75 selesai: Rumor Doppelgänger Hitler (Bagian II)
37/75 selesai: Rumor Doppelgänger Hitler (Bagian I)
38/75 selesai: Memperingati Peristiwa Asa Bafagih
39/75 selesai: Kegigihan Asa Bafagih
40/75 selesai: Melanggengkan Praktik Kamp Interniran
41/75 selesai: Catatan Snouck Hurgronje Tentang Kebiasaan Umat Is
42/75 selesai: 27 Maret 1968: Wilhelmus Zakaria Johannes Menjadi
43/75 selesai: Ahem Erningpraja Salah Satu Pejuang THR
44/75 selesai: Snouck Hurgronje di Jeddah dan Makkah
45/75 selesai: Di Balik Dukungan Palestina terhadap Revolusi Keme
46/75 selesai: Kisah Begundal Revolusi Sosial di Langkat
47/75 selesai: Masa Pahit Kesultanan Langkat
48/75 selesai: Cornelis Speelman di Tengah Kemelut Mataram
49/75 selesai: Try Sutrisno, Wapres Paling Beken di Era Orde Baru
50/75 selesai: Jalan Cornelis Speelman Menjadi Gubernur Jenderal
51/75 selesai: Sebelum Ali Khamenei Jadi Pemimpin Tertinggi
52/75 selesai: Sersan Mayor Tentara Kolonial Jadi Presiden
53/75 selesai: Kala Sultan Mehmed Memburu Dracula di Bulan Puasa
54/75 selesai: Kho Tjoen Gwan dari Jago Kungfu ke Pendekar Pena
55/75 selesai: Pangeran Andrew di Lingkaran Jeffrey Epstein
56/75 selesai: Tragedi Jago Kuntau Tangerang di Masa Revolusi
57/75 selesai: Soebandrio Ujung Tombak Politik Luar Negeri Sukarn
58/75 selesai: Ruhana Kudus Bukan Sekadar Wartawan Perempuan Pert
59/75 selesai: Kisah Pertemuan Pangeran Makassar dan Padri Spanyo
60/75 selesai: Sutan Sjahrir dan Manifesto Antifasis
61/75 selesai: Sudomo Sumber Berita
62/75 selesai: Jejak Raja dan Ratu Belgia di Indonesia
63/75 selesai: Pasang Surut Hubungan Indonesia dan Iran
64/75 selesai: Greenland Dikuasai Denmark, Diancam Amerika Serika
65/75 selesai: Menghidupkan Kembali Spirit Patrice Lumumba
66/75 selesai: Tukang Jahit Jadi Raja
67/75 selesai: Sekilas Perjalanan Sukarno ke Venezuela
68/75 selesai: Bung Karno Berhadapan dengan Bos Preman Medan
69/75 selesai: “Cari Adil, Dapat Bedil” dari Lurah Blasteran
70/75 selesai: Secuplik Kesan Istri Nixon Ngetrip ke Indonesia
71/75 selesai: Akhir Perlawanan Tuan Rondahaim Terhadap Belanda
72/75 selesai: Persekutuan Tuan Rondahaim dan Sisingamangaraja
73/75 selesai: Wanita Perkasa Pembela Jelata
74/75 selesai: Prajurit Keraton Ikut PKI
75/75 selesai: Perang Jawa Memicu Kemerdekaan Belgia dari Belanda

,Judul Artikel,Link Halaman,Penjelasan
0,Istilah “Bersiap” yang Problematik,https://www.historia.id/article/istilah-bersia...,"Ada problem apa di balik istilah ""bersiap"" yan..."
1,Senjakala Semaoen,https://www.historia.id/article/senjakala-semaoen,Kepulangan Semaoen ke Indonesia setelah 33 tah...
2,Anjangsana Ahmad Subardjo di Negeri Persia,https://www.historia.id/article/anjangsana-ahm...,Di tengah perseteruan PM Mosaddegh dan Shah Re...
3,"Semaoen dan Sneevliet, Simbiosis Mutualisme Me...",https://www.historia.id/article/semaoen-dan-sn...,Beranjak remaja di tengah berseminya pergeraka...
4,Ahmad Subardjo di Palestina,https://www.historia.id/article/ahmad-subardjo...,Pemerintah Indonesia mendesak dunia Islam lebi...
...,...,...,...
70,Akhir Perlawanan Tuan Rondahaim Terhadap Belanda,https://www.historia.id/article/akhir-perlawan...,Tuan Rondahaim melawan Belanda di Simalungun h...
71,Persekutuan Tuan Rondahaim dan Sisingamangaraja,https://www.historia.id/article/persekutuan-tu...,Tuan Rondahaim dan Sisingamangaraja bersekutu ...
72,Wanita Perkasa Pembela Jelata,https://www.historia.id/article/wanita-perkasa...,"S.K. Trimurti pejuang perempuan yang komplet, ..."
73,Prajurit Keraton Ikut PKI,https://www.historia.id/article/prajurit-kerat...,Dua anggota legiun Mangkunegaran ikut serta ge...
74,Perang Jawa Memicu Kemerdekaan Belgia dari Bel...,https://www.historia.id/article/perang-jawa-me...,Hubungan diplomatik Indonesia dan Belgia secar...

**Scraping with API**

In [11]:
import requests
url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=idr'
api_request = requests.get(url)
api_request

In [13]:
api_request_json = api_request.json()
api_request_json

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 1536840396,
  'market_cap': 30869342257205020,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 30869376064829380,
  'total_volume': 823589169151152,
  'high_24h': 1556016791,
  'low_24h': 1516414838,
  'price_change_24h': 9480984,
  'price_change_percentage_24h': 0.32585,
  'market_cap_change_24h': 188543660385332,
  'market_cap_change_percentage_24h': 0.61453,
  'circulating_supply': 20087940.0,
  'total_supply': 20087984.0,
  'max_supply': 21000000.0,
  'ath': 2091468459,
  'ath_change_percentage': -26.5186,
  'ath_date': '2025-10-06T10:57:42.000Z',
  'atl': 658780,
  'atl_change_percentage': 233185.83924,
  'atl_date': '2013-07-04T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 48753996,
  'market_cap': 5950638215802515,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 5950638215802515,
  'total_volume': 324036225188404,
  'high_24h': 49968252,
  'low_24h': 48394875,
  'price_change_24h': -238140.91551008075,
  'price_change_percentage_24h': -0.82612,
  'market_cap_change_24h': -29716624406666.0,
  'market_cap_change_percentage_24h': -0.4969,
  'circulating_supply': 122070499.19308256,
  'total_supply': 122070499.1930825,
  'max_supply': None,
  'ath': 80291629,
  'ath_change_percentage': -39.27886,
  'ath_date': '2025-08-24T11:21:03.000Z',
  'atl': 5876.48,
  'atl_change_percentage': 829546.60145,
  'atl_date': '2015-10-19T16:00:00.000Z',
  'roi': {'times': 41.41170353581274,
   'currency': 'btc',
   'percentage': 4141.170353581274},
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 17816.23,
  'market_cap': 3267286193475548,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 3364688441338229,
  'total_volume': 1464358821542845,
  'high_24h': 17818.87,
  'low_24h': 17811.04,
  'price_change_24h': 0.066241,
  'price_change_percentage_24h': -0.30959,
  'market_cap_change_24h': 74454605058,
  'market_cap_change_percentage_24h': 0.00228,
  'circulating_supply': 183384649781.69382,
  'total_supply': 188851595759.0362,
  'max_supply': None,
  'ath': 19797.9,
  'ath_change_percentage': -10.00947,
  'ath_date': '2025-01-25T08:51:57.000Z',
  'atl': 7740.52,
  'atl_change_percentage': 130.16838,
  'atl_date': '2015-03-01T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 14016673,
  'market_cap': 1866642990853211,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 1866642961134968,
  'total_volume': 25327538404625,
  'high_24h': 14374494,
  'low_24h': 13930355,
  'price_change_24h': -240656.32515107468,
  'price_change_percentage_24h': -1.99671,
  'market_cap_change_24h': -31865180440854.0,
  'market_cap_change_percentage_24h': -1.67843,
  'circulating_supply': 133160063.39,
  'total_supply': 133160056.04,
  'max_supply': 200000000.0,
  'ath': 22732156,
  'ath_change_percentage': -38.33989,
  'ath_date': '2025-10-13T00:41:24.000Z',
  'atl': 538.01,
  'atl_change_percentage': 2605197.43594,
  'atl_date': '2017-10-18T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 27826,
  'market_cap': 1749234646203652,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 2781496697349602,
  'total_volume': 111879136193368,
  'high_24h': 28377,
  'low_24h': 26519,
  'price_change_24h': 1161.65,
  'price_change_percentage_24h': 4.09205,
  'market_cap_change_24h': 72614901062862,
  'market_cap_change_percentage_24h': 4.33103,
  'circulating_supply': 62879209849.0,
  'total_supply': 99985622230.0,
  'max_supply': 100000000000.0,
  'ath': 59550,
  'ath_change_percentage': -53.27286,
  'ath_date': '2025-07-17T17:00:37.000Z',
  'atl': 26.88,
  'atl_change_percentage': 103405.38032,
  'atl_date': '2013-08-15T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 17816.73,
  'market_cap': 1329228756558956,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 1329301067826474,
  'total_volume': 385493254636497,
  'high_24h': 17819.22,
  'low_24h': 17812.25,
  'price_change_24h': 0.062706,
  'price_change_percentage_24h': -0.31026,
  'market_cap_change_24h': 7059179211025,
  'market_cap_change_percentage_24h': 0.53391,
  'circulating_supply': 74604459959.80891,
  'total_supply': 74776133515.82288,
  'max_supply': None,
  'ath': 18309.61,
  'ath_change_percentage': -2.69193,
  'ath_date': '2026-07-15T22:39:40.000Z',
  'atl': 12829.05,
  'atl_change_percentage': 38.87797,
  'atl_date': '2021-05-19T05:14:05.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 2083645,
  'market_cap': 1224072774418258,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 1322046545523734,
  'total_volume': 88615881430427,
  'high_24h': 2136345,
  'low_24h': 2059320,
  'price_change_24h': -12656.843363951193,
  'price_change_percentage_24h': -0.95203,
  'market_cap_change_24h': -7373298310225.75,
  'market_cap_change_percentage_24h': -0.59875,
  'circulating_supply': 587507671.2531247,
  'total_supply': 634531253.2596909,
  'max_supply': None,
  'ath': 4805355,
  'ath_change_percentage': -56.63909,
  'ath_date': '2025-01-19T03:15:27.000Z',
  'atl': 7456.91,
  'atl_change_percentage': 27842.49207,
  'atl_date': '2020-05-11T11:35:23.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 6081.9,
  'market_cap': 577556213198118,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 577556194686374,
  'total_volume': 11095357681646,
  'high_24h': 6221.55,
  'low_24h': 6081.38,
  'price_change_24h': -68.2678597938193,
  'price_change_percentage_24h': -1.42029,
  'market_cap_change_24h': -6466276141969.75,
  'market_cap_change_percentage_24h': -1.1072,
  'circulating_supply': 94961729708.24278,
  'total_supply': 94961737543.34338,
  'max_supply': None,
  'ath': 6881.98,
  'ath_change_percentage': -11.62571,
  'ath_date': '2024-12-03T16:10:40.000Z',
  'atl': 24.4,
  'atl_change_percentage': 24822.43787,
  'atl_date': '2017-11-11T16:00:00.000Z',
  'roi': {'times': 178.63495574112883,
   'currency': 'usd',
   'percentage': 17863.495574112883},
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/Brandmark-Yellow_%281%29.png?1785810558',
  'current_price': 27379263,
  'market_cap': 464224485100895,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 464262539557918,
  'total_volume': 25011100169361,
  'high_24h': 27737914,
  'low_24h': 25731795,
  'price_change_24h': 746564,
  'price_change_percentage_24h': 2.40762,
  'market_cap_change_24h': 13003935568821,
  'market_cap_change_percentage_24h': 2.88195,
  'circulating_supply': 16945106.4155448,
  'total_supply': 16946564.2280448,
  'max_supply': 21000000.0,
  'ath': 41265193,
  'ath_change_percentage': -33.65047,
  'ath_date': '2016-10-28T16:00:00.000Z',
  'atl': 262193,
  'atl_change_percentage': 10342.42514,
  'atl_date': '2024-07-04T20:22:29.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 17943.35,
  'market_cap': 412082471657392,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 412082471657392,
  'total_volume': 895148157961,
  'high_24h': 18430.93,
  'low_24h': 17926.52,
  'price_change_24h': -535.4622657448745,
  'price_change_percentage_24h': -3.19852,
  'market_cap_change_24h': -8573336576657.4375,
  'market_cap_change_percentage_24h': -2.03809,
  'circulating_supply': 22966221270.418,
  'total_supply': 22966221270.418,
  'max_supply': None,
  'ath': 19060.59,
  'ath_change_percentage': -5.86154,
  'ath_date': '2026-08-03T14:27:20.000Z',
  'atl': 2586.43,
  'atl_change_percentage': 593.75063,
  'atl_date': '2025-10-31T07:23:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 1684311,
  'market_cap': 374621016707420,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1608833466875125,
  'total_volume': 20499214792482,
  'high_24h': 1708678,
  'low_24h': 1640363,
  'price_change_24h': 26762,
  'price_change_percentage_24h': 1.27507,
  'market_cap_change_24h': 5906494616550,
  'market_cap_change_percentage_24h': 1.60192,
  'circulating_supply': 222445714.07414138,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 1716212,
  'ath_change_percentage': -1.85881,
  'ath_date': '2026-09-21T11:21:00.000Z',
  'atl': 60388,
  'atl_change_percentage': 2689.13264,
  'atl_date': '2024-11-29T01:30:30.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 1768.86,
  'market_cap': 275983093214521,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 303777840546944,
  'total_volume': 50366566915038,
  'high_24h': 1881.1,
  'low_24h': 1720.62,
  'price_change_24h': 45.54,
  'price_change_percentage_24h': 2.31407,
  'market_cap_change_24h': 7130988954512,
  'market_cap_change_percentage_24h': 2.65238,
  'circulating_supply': 156021246383.70517,
  'total_supply': 156022946383.7052,
  'max_supply': None,
  'ath': 10338.3,
  'ath_change_percentage': -82.89017,
  'ath_date': '2021-05-07T21:08:23.000Z',
  'atl': 1.13,
  'atl_change_percentage': 156204.25812,
  'atl_date': '2015-05-05T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 10150233,
  'market_cap': 190929143119325,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 190929502473097,
  'total_volume': 3013755813944,
  'high_24h': 10708572,
  'low_24h': 9847064,
  'price_change_24h': -5154.110378263518,
  'price_change_percentage_24h': -0.47338,
  'market_cap_change_24h': -69353573246.71875,
  'market_cap_change_percentage_24h': -0.03631,
  'circulating_supply': 18808020.71149838,
  'total_supply': 18808072.30994128,
  'max_supply': None,
  'ath': 13447016,
  'ath_change_percentage': -24.51683,
  'ath_date': '2026-01-14T11:34:07.000Z',
  'atl': 2751.67,
  'atl_change_percentage': 368775.89594,
  'atl_date': '2015-01-13T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 1542346,
  'market_cap': 183314044375168,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 452564833965178,
  'total_volume': 2957995063477,
  'high_24h': 1566411,
  'low_24h': 1524615,
  'price_change_24h': 3999.91,
  'price_change_percentage_24h': -0.04317,
  'market_cap_change_24h': 423153769379,
  'market_cap_change_percentage_24h': 0.23137,
  'circulating_supply': 118852171.0,
  'total_supply': 293421670.0,
  'max_supply': 400000000.0,
  'ath': 1570962,
  'ath_change_percentage': -1.82152,
  'ath_date': '2026-09-21T20:29:10.000Z',
  'atl': 46216,
  'atl_change_percentage': 3237.28499,
  'atl_date': '2022-09-21T15:38:03.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 230783,
  'market_cap': 172643130010855,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 230775480331596,
  'total_volume': 11833149933322,
  'high_24h': 236262,
  'low_24h': 227328,
  'price_change_24h': -572.427685093513,
  'price_change_percentage_24h': -0.58852,
  'market_cap_change_24h': -434094394333.78125,
  'market_cap_change_percentage_24h': -0.25081,
  'circulating_supply': 748099970.424884,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 752768,
  'ath_change_percentage': -69.34204,
  'ath_date': '2021-05-09T16:13:57.000Z',
  'atl': 2001.37,
  'atl_change_percentage': 11431.27225,
  'atl_date': '2017-11-28T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 17816.61,
  'market_cap': 170602070587779,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 170672100485669,
  'total_volume': 3763933382446,
  'high_24h': 17823.33,
  'low_24h': 17812.87,
  'price_change_24h': -3.966736167229101,
  'price_change_percentage_24h': -0.33211,
  'market_cap_change_24h': -384411072076.15625,
  'market_cap_change_percentage_24h': -0.22482,
  'circulating_supply': 9575258938.40892,
  'total_supply': 9576464149.406918,
  'max_supply': None,
  'ath': 18315.99,
  'ath_change_percentage': -2.72648,
  'ath_date': '2026-07-15T22:30:40.000Z',
  'atl': 14517.43,
  'atl_change_percentage': 22.72562,
  'atl_date': '2024-10-02T11:53:21.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 239.51,
  'market_cap': 169832531648037,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 273557913146157,
  'total_volume': 238703167979,
  'high_24h': 252.6,
  'low_24h': 238.49,
  'price_change_24h': -13.02177290236142,
  'price_change_percentage_24h': -5.4629,
  'market_cap_change_24h': -9270635744730.625,
  'market_cap_change_percentage_24h': -5.17614,
  'circulating_supply': 709239700254.0453,
  'total_supply': 1142408526965.963,
  'max_supply': 1150000000000.0,
  'ath': 344.1,
  'ath_change_percentage': -30.39644,
  'ath_date': '2026-08-25T19:53:00.000Z',
  'atl': 36.45,
  'atl_change_percentage': 557.15161,
  'atl_date': '2025-09-14T00:56:57.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 4435.25,
  'market_cap': 166424307454909,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 199554516917014,
  'total_volume': 15445920322536,
  'high_24h': 4522.43,
  'low_24h': 4283.67,
  'price_change_24h': 74.59,
  'price_change_percentage_24h': 1.42738,
  'market_cap_change_24h': 2799786378279,
  'market_cap_change_percentage_24h': 1.7111,
  'circulating_supply': 37529061988.535576,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 44039,
  'ath_change_percentage': -89.92884,
  'ath_date': '2021-09-01T22:00:10.000Z',
  'atl': 284.96,
  'atl_change_percentage': 1456.4253,
  'atl_date': '2020-03-12T18:22:55.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 159721,
  'market_cap': 146920884789162,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 157363726751828,
  'total_volume': 2607479631,
  'high_24h': 160442,
  'low_24h': 158096,
  'price_change_24h': 1286.7,
  'price_change_percentage_24h': 0.4992,
  'market_cap_change_24h': 1183640972757,
  'market_cap_change_percentage_24h': 0.81217,
  'circulating_supply': 919857851.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 184516,
  'ath_change_percentage': -13.43758,
  'ath_date': '2026-05-04T09:35:00.000Z',
  'atl': 11148.85,
  'atl_change_percentage': 1332.62522,
  'atl_date': '2019-12-31T04:15:15.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 3792.74,
  'market_cap': 132437180152352,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 189571700178527,
  'total_volume': 7341429290557,
  'high_24h': 3915.65,
  'low_24h': 3674.65,
  'price_change_24h': 52.77,
  'price_change_percentage_24h': 1.06846,
  'market_cap_change_24h': 1978685773777,
  'market_cap_change_percentage_24h': 1.51672,
  'circulating_supply': 34931878784.61168,
  'total_supply': 50001786839.70148,
  'max_supply': None,
  'ath': 11808.12,
  'ath_change_percentage': -67.88027,
  'ath_date': '2018-01-02T16:00:00.000Z',
  'atl': 6.19,
  'atl_change_percentage': 61124.25001,
  'atl_date': '2015-03-04T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 5806207,
  'market_cap': 116808759494129,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 116808759494129,
  'total_volume': 15011879019543,
  'high_24h': 5854886,
  'low_24h': 4664692,
  'price_change_24h': 1095543,
  'price_change_percentage_24h': 22.74019,
  'market_cap_change_24h': 22161374649333,
  'market_cap_change_percentage_24h': 23.41467,
  'circulating_supply': 20092765.52165077,
  'total_supply': 20092803.02165077,
  'max_supply': 21000000.0,
  'ath': 51400851,
  'ath_change_percentage': -88.70406,
  'ath_date': '2017-12-19T16:00:00.000Z',
  'atl': 1121286,
  'atl_change_percentage': 417.81673,
  'atl_date': '2018-12-15T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'near',
  'symbol': 'near',
  'name': 'NEAR Protocol',
  'image': 'https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367',
  'current_price': 78657,
  'market_cap': 102882401023905,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 102882401023905,
  'total_volume': 32517698440931,
  'high_24h': 82861,
  'low_24h': 69832,
  'price_change_24h': 6194.04,
  'price_change_percentage_24h': 8.19802,
  'market_cap_change_24h': 8178964708571,
  'market_cap_change_percentage_24h': 8.6364,
  'circulating_supply': 1306999731.0,
  'total_supply': 1306999679.0,
  'max_supply': None,
  'ath': 292609,
  'ath_change_percentage': -73.11866,
  'ath_date': '2022-01-16T14:09:45.000Z',
  'atl': 7636.89,
  'atl_change_percentage': 929.96311,
  'atl_date': '2020-11-04T07:44:20.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:12:10.000Z'},
 {'id': 'uniswap',

In [16]:
for coin in api_request_json:
  print(coin.get('name'))

Bitcoin
Ethereum
Tether
BNB
XRP
USDC
Solana
TRON
Zcash
Figure Heloc
Hyperliquid
Dogecoin
Monero
WhiteBIT Coin
Chainlink
USDS
Rain
Cardano
LEO Token
Stellar
Bitcoin Cash
NEAR Protocol
Uniswap
Avalanche
Ethena USDe
Litecoin
Dai
Canton
USD1
Hedera
Sui
Gram (prev. Toncoin)
Shiba Inu
Bittensor
Cronos
Global Dollar
MemeCore
PayPal USD
Tether Gold
OKB
Circle USYC
Ripple USD
Bitway
BlackRock USD Institutional Digital Liquidity Fund
Ondo US Dollar Yield
Aave
Mantle
Ondo
Ethena
Pump.fun
Pepe
Polkadot
Aster
PAX Gold
World Liberty Financial
Morpho
Worldcoin
Internet Computer
Sky
HTX DAO
USDD
Venice Token
Bitget Token
Ethereum Classic
Arbitrum
Spiko Amundi Overnight Swap Fund (EUR)
United Stables
USDGO
Falcon USD
BFUSD
Akedo
Lighter
Gate
Kaspa
POL (ex-MATIC)
Quant
KuCoin
Pi Network
Algorand
Blockchain Capital
Jupiter
Render
JUST
Cosmos Hub
NEXO
Filecoin
PancakeSwap
Spiko EU T-Bills Money Market Fund
VeChain
Janus Henderson Anemoy AAA CLO Fund
Injective
Dash
Invesco Short Duration US Government Securities Fund
GHO
Aerodrome Finance
Aptos
Ether.fi
​​Stable
Stacks
XDC Network

In [18]:
api_request = requests.get(url, params={'per_page': 15})
api_data = api_request.json()
api_data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 1533615826,
  'market_cap': 30808228362106312,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 30808228362106312,
  'total_volume': 819247941713164,
  'high_24h': 1555451395,
  'low_24h': 1515863832,
  'price_change_24h': 5694936,
  'price_change_percentage_24h': 0.01374,
  'market_cap_change_24h': 116151093201524,
  'market_cap_change_percentage_24h': 0.37844,
  'circulating_supply': 20087962.0,
  'total_supply': 20087984.0,
  'max_supply': 21000000.0,
  'ath': 2091468459,
  'ath_change_percentage': -26.67277,
  'ath_date': '2025-10-06T10:57:42.000Z',
  'atl': 658780,
  'atl_change_percentage': 232696.36327,
  'atl_date': '2013-07-04T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 48638201,
  'market_cap': 5937110081375364,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 5937110081375364,
  'total_volume': 320861351002215,
  'high_24h': 49950095,
  'low_24h': 48377290,
  'price_change_24h': -509431.83460795134,
  'price_change_percentage_24h': -1.45512,
  'market_cap_change_24h': -62225815522956.0,
  'market_cap_change_percentage_24h': -1.03721,
  'circulating_supply': 122070499.19308256,
  'total_supply': 122070499.1930825,
  'max_supply': None,
  'ath': 80291629,
  'ath_change_percentage': -39.42307,
  'ath_date': '2025-08-24T11:21:03.000Z',
  'atl': 5876.48,
  'atl_change_percentage': 827576.1233,
  'atl_date': '2015-10-19T16:00:00.000Z',
  'roi': {'times': 41.388570833771944,
   'currency': 'btc',
   'percentage': 4138.857083377195},
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 17809.57,
  'market_cap': 3265904235550411,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 3363265285366644,
  'total_volume': 1454962028522946,
  'high_24h': 17812.4,
  'low_24h': 17804.57,
  'price_change_24h': 0.629813,
  'price_change_percentage_24h': -0.34555,
  'market_cap_change_24h': 18241675734,
  'market_cap_change_percentage_24h': 0.00056,
  'circulating_supply': 183384649781.69382,
  'total_supply': 188851595759.0362,
  'max_supply': None,
  'ath': 19797.9,
  'ath_change_percentage': -10.04314,
  'ath_date': '2025-01-25T08:51:57.000Z',
  'atl': 7740.52,
  'atl_change_percentage': 130.08227,
  'atl_date': '2015-03-01T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 13986475,
  'market_cap': 1862470370513480,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 1862470340861668,
  'total_volume': 25188092979143,
  'high_24h': 14369271,
  'low_24h': 13925293,
  'price_change_24h': -294275.73435222916,
  'price_change_percentage_24h': -2.38602,
  'market_cap_change_24h': -39156551342050.25,
  'market_cap_change_percentage_24h': -2.05911,
  'circulating_supply': 133160063.39,
  'total_supply': 133160056.04,
  'max_supply': 200000000.0,
  'ath': 22732156,
  'ath_change_percentage': -38.47273,
  'ath_date': '2025-10-13T00:41:24.000Z',
  'atl': 538.01,
  'atl_change_percentage': 2599584.42725,
  'atl_date': '2017-10-18T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 27663,
  'market_cap': 1740008347605949,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 2766825755898741,
  'total_volume': 111363544726925,
  'high_24h': 28367,
  'low_24h': 26510,
  'price_change_24h': 982.59,
  'price_change_percentage_24h': 3.31056,
  'market_cap_change_24h': 62369191168077,
  'market_cap_change_percentage_24h': 3.71768,
  'circulating_supply': 62879209849.0,
  'total_supply': 99985622230.0,
  'max_supply': 100000000000.0,
  'ath': 59550,
  'ath_change_percentage': -53.54633,
  'ath_date': '2025-07-17T17:00:37.000Z',
  'atl': 26.88,
  'atl_change_percentage': 102799.60333,
  'atl_date': '2013-08-15T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 17810.1,
  'market_cap': 1328673354195561,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 1328745635248679,
  'total_volume': 383147394070845,
  'high_24h': 17812.74,
  'low_24h': 17805.78,
  'price_change_24h': 0.639291,
  'price_change_percentage_24h': -0.34692,
  'market_cap_change_24h': 7038451920987,
  'market_cap_change_percentage_24h': 0.53256,
  'circulating_supply': 74604459959.80891,
  'total_supply': 74776133515.82288,
  'max_supply': None,
  'ath': 18309.61,
  'ath_change_percentage': -2.72813,
  'ath_date': '2026-07-15T22:39:40.000Z',
  'atl': 12829.05,
  'atl_change_percentage': 38.82631,
  'atl_date': '2021-05-19T05:14:05.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 2080347,
  'market_cap': 1222114823370739,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 1319931922912966,
  'total_volume': 88162410743847,
  'high_24h': 2135569,
  'low_24h': 2058571,
  'price_change_24h': -20058.01166188903,
  'price_change_percentage_24h': -1.3168,
  'market_cap_change_24h': -11741138491636.5,
  'market_cap_change_percentage_24h': -0.95158,
  'circulating_supply': 587507652.9072297,
  'total_supply': 634531253.2596909,
  'max_supply': None,
  'ath': 4805355,
  'ath_change_percentage': -56.70774,
  'ath_date': '2025-01-19T03:15:27.000Z',
  'atl': 7456.91,
  'atl_change_percentage': 27798.25401,
  'atl_date': '2020-05-11T11:35:23.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 6074.84,
  'market_cap': 576801200667148,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 576801182179605,
  'total_volume': 11113256020690,
  'high_24h': 6219.29,
  'low_24h': 6079.17,
  'price_change_24h': -71.7277667490298,
  'price_change_percentage_24h': -1.51797,
  'market_cap_change_24h': -6878980527902.875,
  'market_cap_change_percentage_24h': -1.17855,
  'circulating_supply': 94961729708.24278,
  'total_supply': 94961737543.34338,
  'max_supply': None,
  'ath': 6881.98,
  'ath_change_percentage': -11.72837,
  'ath_date': '2024-12-03T16:10:40.000Z',
  'atl': 24.4,
  'atl_change_percentage': 24793.48831,
  'atl_date': '2017-11-11T16:00:00.000Z',
  'roi': {'times': 178.53884027800416,
   'currency': 'usd',
   'percentage': 17853.884027800417},
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/Brandmark-Yellow_%281%29.png?1785810558',
  'current_price': 27444266,
  'market_cap': 465404163306442,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 465442314466709,
  'total_volume': 26758719379885,
  'high_24h': 27727835,
  'low_24h': 25722445,
  'price_change_24h': 754950,
  'price_change_percentage_24h': 2.66362,
  'market_cap_change_24h': 13224373230415,
  'market_cap_change_percentage_24h': 2.92458,
  'circulating_supply': 16945106.4155448,
  'total_supply': 16946564.2280448,
  'max_supply': 21000000.0,
  'ath': 41265193,
  'ath_change_percentage': -33.49294,
  'ath_date': '2016-10-28T16:00:00.000Z',
  'atl': 262193,
  'atl_change_percentage': 10367.2175,
  'atl_date': '2024-07-04T20:22:29.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 17929.23,
  'market_cap': 411779076622481,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 411779076622481,
  'total_volume': 954253597437,
  'high_24h': 18424.23,
  'low_24h': 17920.0,
  'price_change_24h': -543.6955080699954,
  'price_change_percentage_24h': -3.28142,
  'market_cap_change_24h': -8742751702184.1875,
  'market_cap_change_percentage_24h': -2.07902,
  'circulating_supply': 22966221270.418,
  'total_supply': 22966221270.418,
  'max_supply': None,
  'ath': 19060.59,
  'ath_change_percentage': -5.93562,
  'ath_date': '2026-08-03T14:27:20.000Z',
  'atl': 2586.43,
  'atl_change_percentage': 593.20475,
  'atl_date': '2025-10-31T07:23:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 1686379,
  'market_cap': 375168183695279,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1611183309843827,
  'total_volume': 20602242766838,
  'high_24h': 1708057,
  'low_24h': 1639767,
  'price_change_24h': 31408,
  'price_change_percentage_24h': 1.52909,
  'market_cap_change_24h': 7027122987634,
  'market_cap_change_percentage_24h': 1.90881,
  'circulating_supply': 222445714.07414138,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 1716212,
  'ath_change_percentage': -1.7383,
  'ath_date': '2026-09-21T11:21:00.000Z',
  'atl': 60388,
  'atl_change_percentage': 2692.55749,
  'atl_date': '2024-11-29T01:30:30.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 1760.83,
  'market_cap': 274710579936398,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 302374476329977,
  'total_volume': 51759839258233,
  'high_24h': 1880.41,
  'low_24h': 1719.99,
  'price_change_24h': 34.33,
  'price_change_percentage_24h': 1.69181,
  'market_cap_change_24h': 5361407913606,
  'market_cap_change_percentage_24h': 1.9905,
  'circulating_supply': 156022636383.70523,
  'total_supply': 156022946383.7052,
  'max_supply': None,
  'ath': 10338.3,
  'ath_change_percentage': -82.96786,
  'ath_date': '2021-05-07T21:08:23.000Z',
  'atl': 1.13,
  'atl_change_percentage': 155494.60824,
  'atl_date': '2015-05-05T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 10160020,
  'market_cap': 191164462461380,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 191164474652983,
  'total_volume': 3018863319123,
  'high_24h': 10704681,
  'low_24h': 9843486,
  'price_change_24h': -5901.026427129284,
  'price_change_percentage_24h': -0.36385,
  'market_cap_change_24h': -32148073465.4375,
  'market_cap_change_percentage_24h': -0.01681,
  'circulating_supply': 18808054.91117584,
  'total_supply': 18808072.30994128,
  'max_supply': None,
  'ath': 13447016,
  'ath_change_percentage': -24.44405,
  'ath_date': '2026-01-14T11:34:07.000Z',
  'atl': 2751.67,
  'atl_change_percentage': 369131.56387,
  'atl_date': '2015-01-13T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 1539761,
  'market_cap': 183007749249451,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 451808654027154,
  'total_volume': 2938898900482,
  'high_24h': 1565841,
  'low_24h': 1524061,
  'price_change_24h': 664.59,
  'price_change_percentage_24h': -0.32397,
  'market_cap_change_24h': 27645495260,
  'market_cap_change_percentage_24h': 0.01511,
  'circulating_supply': 118852171.0,
  'total_supply': 293421670.0,
  'max_supply': 400000000.0,
  'ath': 1570962,
  'ath_change_percentage': -1.98606,
  'ath_date': '2026-09-21T20:29:10.000Z',
  'atl': 46216,
  'atl_change_percentage': 3231.6918,
  'atl_date': '2022-09-21T15:38:03.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 229729,
  'market_cap': 171824088635025,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 229680651554414,
  'total_volume': 11740788431080,
  'high_24h': 236176,
  'low_24h': 227245,
  'price_change_24h': -1873.225772128877,
  'price_change_percentage_24h': -1.1355,
  'market_cap_change_24h': -1437453285466.6562,
  'market_cap_change_percentage_24h': -0.82964,
  'circulating_supply': 748099970.424884,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 752768,
  'ath_change_percentage': -69.48211,
  'ath_date': '2021-05-09T16:13:57.000Z',
  'atl': 2001.37,
  'atl_change_percentage': 11378.58746,
  'atl_date': '2017-11-28T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'}]

In [19]:
url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=idr'
api_request = requests.get(url, params = {'limit':15})
api_request.json()

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 1533721737,
  'market_cap': 30810355965551724,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 30810355965551724,
  'total_volume': 819304518635503,
  'high_24h': 1555558814,
  'low_24h': 1515968517,
  'price_change_24h': 5695329,
  'price_change_percentage_24h': -0.01223,
  'market_cap_change_24h': 116159114547744,
  'market_cap_change_percentage_24h': 0.37844,
  'circulating_supply': 20087962.0,
  'total_supply': 20087984.0,
  'max_supply': 21000000.0,
  'ath': 2091468459,
  'ath_change_percentage': -26.66771,
  'ath_date': '2025-10-06T10:57:42.000Z',
  'atl': 658780,
  'atl_change_percentage': 232712.44009,
  'atl_date': '2013-07-04T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 48641560,
  'market_cap': 5937520095729856,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 5937520095729856,
  'total_volume': 320883509553751,
  'high_24h': 49953545,
  'low_24h': 48380631,
  'price_change_24h': -509467.0157587081,
  'price_change_percentage_24h': -1.4245,
  'market_cap_change_24h': -62230112811912.0,
  'market_cap_change_percentage_24h': -1.03721,
  'circulating_supply': 122070499.19308256,
  'total_supply': 122070499.1930825,
  'max_supply': None,
  'ath': 80291629,
  'ath_change_percentage': -39.41889,
  'ath_date': '2025-08-24T11:21:03.000Z',
  'atl': 5876.48,
  'atl_change_percentage': 827633.28226,
  'atl_date': '2015-10-19T16:00:00.000Z',
  'roi': {'times': 41.42455665163366,
   'currency': 'btc',
   'percentage': 4142.455665163366},
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 17810.8,
  'market_cap': 3266129777539463,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 3363497551069328,
  'total_volume': 1455062507595888,
  'high_24h': 17813.63,
  'low_24h': 17805.8,
  'price_change_24h': 0.629856,
  'price_change_percentage_24h': -0.3515,
  'market_cap_change_24h': 18242935497,
  'market_cap_change_percentage_24h': 0.00056,
  'circulating_supply': 183384649781.69382,
  'total_supply': 188851595759.0362,
  'max_supply': None,
  'ath': 19797.9,
  'ath_change_percentage': -10.03693,
  'ath_date': '2025-01-25T08:51:57.000Z',
  'atl': 7740.52,
  'atl_change_percentage': 130.09816,
  'atl_date': '2015-03-01T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 13987441,
  'market_cap': 1862598991943142,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 1862598962289282,
  'total_volume': 25189832458375,
  'high_24h': 14370263,
  'low_24h': 13926255,
  'price_change_24h': -294296.05691212974,
  'price_change_percentage_24h': -2.44871,
  'market_cap_change_24h': -39159255477211.0,
  'market_cap_change_percentage_24h': -2.05911,
  'circulating_supply': 133160063.39,
  'total_supply': 133160056.04,
  'max_supply': 200000000.0,
  'ath': 22732156,
  'ath_change_percentage': -38.46848,
  'ath_date': '2025-10-13T00:41:24.000Z',
  'atl': 538.01,
  'atl_change_percentage': 2599763.96037,
  'atl_date': '2017-10-18T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 27665,
  'market_cap': 1740128511859210,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 2767016831735427,
  'total_volume': 111371235447036,
  'high_24h': 28369,
  'low_24h': 26512,
  'price_change_24h': 982.65,
  'price_change_percentage_24h': 3.42263,
  'market_cap_change_24h': 62373498358496,
  'market_cap_change_percentage_24h': 3.71768,
  'circulating_supply': 62879209849.0,
  'total_supply': 99985622230.0,
  'max_supply': 100000000000.0,
  'ath': 59550,
  'ath_change_percentage': -53.54312,
  'ath_date': '2025-07-17T17:00:37.000Z',
  'atl': 26.88,
  'atl_change_percentage': 102806.70953,
  'atl_date': '2013-08-15T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 17811.33,
  'market_cap': 1328765111825145,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 1328837397869963,
  'total_volume': 383173854070626,
  'high_24h': 17813.97,
  'low_24h': 17807.01,
  'price_change_24h': 0.639335,
  'price_change_percentage_24h': -0.35043,
  'market_cap_change_24h': 7038937993551,
  'market_cap_change_percentage_24h': 0.53256,
  'circulating_supply': 74604459959.80891,
  'total_supply': 74776133515.82288,
  'max_supply': None,
  'ath': 18309.61,
  'ath_change_percentage': -2.72142,
  'ath_date': '2026-07-15T22:39:40.000Z',
  'atl': 12829.05,
  'atl_change_percentage': 38.83589,
  'atl_date': '2021-05-19T05:14:05.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 2080490,
  'market_cap': 1222199222112475,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 1320023076862939,
  'total_volume': 88168499203288,
  'high_24h': 2135716,
  'low_24h': 2058714,
  'price_change_24h': -20059.396859837463,
  'price_change_percentage_24h': -1.31657,
  'market_cap_change_24h': -11741949329780.75,
  'market_cap_change_percentage_24h': -0.95158,
  'circulating_supply': 587507652.9072297,
  'total_supply': 634531253.2596909,
  'max_supply': None,
  'ath': 4805355,
  'ath_change_percentage': -56.70475,
  'ath_date': '2025-01-19T03:15:27.000Z',
  'atl': 7456.91,
  'atl_change_percentage': 27800.18065,
  'atl_date': '2020-05-11T11:35:23.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 6075.26,
  'market_cap': 576841034318322,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 576841015829502,
  'total_volume': 11114023497531,
  'high_24h': 6219.72,
  'low_24h': 6079.59,
  'price_change_24h': -71.7327202387878,
  'price_change_percentage_24h': -1.50418,
  'market_cap_change_24h': -6879455587438.875,
  'market_cap_change_percentage_24h': -1.17855,
  'circulating_supply': 94961729708.24278,
  'total_supply': 94961737543.34338,
  'max_supply': None,
  'ath': 6881.98,
  'ath_change_percentage': -11.72227,
  'ath_date': '2024-12-03T16:10:40.000Z',
  'atl': 24.4,
  'atl_change_percentage': 24795.20744,
  'atl_date': '2017-11-11T16:00:00.000Z',
  'roi': {'times': 178.54096621130867,
   'currency': 'usd',
   'percentage': 17854.09662113087},
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/Brandmark-Yellow_%281%29.png?1785810558',
  'current_price': 27446162,
  'market_cap': 465436303924518,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 465474457719487,
  'total_volume': 26760567325923,
  'high_24h': 27729750,
  'low_24h': 25724221,
  'price_change_24h': 755002,
  'price_change_percentage_24h': 2.35882,
  'market_cap_change_24h': 13225286500134,
  'market_cap_change_percentage_24h': 2.92458,
  'circulating_supply': 16945106.4155448,
  'total_supply': 16946564.2280448,
  'max_supply': 21000000.0,
  'ath': 41265193,
  'ath_change_percentage': -33.48835,
  'ath_date': '2016-10-28T16:00:00.000Z',
  'atl': 262193,
  'atl_change_percentage': 10367.94036,
  'atl_date': '2024-07-04T20:22:29.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 17930.47,
  'market_cap': 411807513914359,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 411807513914359,
  'total_volume': 954319497794,
  'high_24h': 18425.5,
  'low_24h': 17921.24,
  'price_change_24h': -543.7330554557993,
  'price_change_percentage_24h': -3.27549,
  'market_cap_change_24h': -8743355472982.8125,
  'market_cap_change_percentage_24h': -2.07902,
  'circulating_supply': 22966221270.418,
  'total_supply': 22966221270.418,
  'max_supply': None,
  'ath': 19060.59,
  'ath_change_percentage': -5.92912,
  'ath_date': '2026-08-03T14:27:20.000Z',
  'atl': 2586.43,
  'atl_change_percentage': 593.25262,
  'atl_date': '2025-10-31T07:23:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 1686495,
  'market_cap': 375194092654109,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1611294577493525,
  'total_volume': 20603665549160,
  'high_24h': 1708175,
  'low_24h': 1639880,
  'price_change_24h': 31411,
  'price_change_percentage_24h': 1.60973,
  'market_cap_change_24h': 7027608277827,
  'market_cap_change_percentage_24h': 1.90881,
  'circulating_supply': 222445714.07414138,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 1716212,
  'ath_change_percentage': -1.73151,
  'ath_date': '2026-09-21T11:21:00.000Z',
  'atl': 60388,
  'atl_change_percentage': 2692.75034,
  'atl_date': '2024-11-29T01:30:30.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 1760.96,
  'market_cap': 274729551334866,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 302395358185632,
  'total_volume': 51763413771219,
  'high_24h': 1880.54,
  'low_24h': 1720.11,
  'price_change_24h': 34.33,
  'price_change_percentage_24h': 1.69189,
  'market_cap_change_24h': 5361778170209,
  'market_cap_change_percentage_24h': 1.9905,
  'circulating_supply': 156022636383.70523,
  'total_supply': 156022946383.7052,
  'max_supply': None,
  'ath': 10338.3,
  'ath_change_percentage': -82.96668,
  'ath_date': '2021-05-07T21:08:23.000Z',
  'atl': 1.13,
  'atl_change_percentage': 155505.35354,
  'atl_date': '2015-05-05T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 10160722,
  'market_cap': 191177664199701,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 191177676392146,
  'total_volume': 3019071800569,
  'high_24h': 10705420,
  'low_24h': 9844166,
  'price_change_24h': -5901.43394956179,
  'price_change_percentage_24h': -0.34268,
  'market_cap_change_24h': -32150293598.03125,
  'market_cap_change_percentage_24h': -0.01681,
  'circulating_supply': 18808054.91117584,
  'total_supply': 18808072.30994128,
  'max_supply': None,
  'ath': 13447016,
  'ath_change_percentage': -24.43883,
  'ath_date': '2026-01-14T11:34:07.000Z',
  'atl': 2751.67,
  'atl_change_percentage': 369157.06285,
  'atl_date': '2015-01-13T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 1539868,
  'market_cap': 183020387688548,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 451839855745009,
  'total_volume': 2939101859618,
  'high_24h': 1565950,
  'low_24h': 1524166,
  'price_change_24h': 664.63,
  'price_change_percentage_24h': -0.34338,
  'market_cap_change_24h': 27647404446,
  'market_cap_change_percentage_24h': 0.01511,
  'circulating_supply': 118852171.0,
  'total_supply': 293421670.0,
  'max_supply': 400000000.0,
  'ath': 1570962,
  'ath_change_percentage': -1.97929,
  'ath_date': '2026-09-21T20:29:10.000Z',
  'atl': 46216,
  'atl_change_percentage': 3231.92188,
  'atl_date': '2022-09-21T15:38:03.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 229745,
  'market_cap': 171835954735168,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 229696513204744,
  'total_volume': 11741599245049,
  'high_24h': 236192,
  'low_24h': 227261,
  'price_change_24h': -1873.3551363221195,
  'price_change_percentage_24h': -1.2283,
  'market_cap_change_24h': -1437552555393.0625,
  'market_cap_change_percentage_24h': -0.82964,
  'circulating_supply': 748099970.424884,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 752768,
  'ath_change_percentage': -69.48,
  'ath_date': '2021-05-09T16:13:57.000Z',
  'atl': 2001.37,
  'atl_change_percentage': 11379.38016,
  'atl_date': '2017-11-28T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 17811.14,
  'market_cap': 170541266208555,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 170611271147050,
  'total_volume': 3780410234852,
  'high_24h': 17818.08,
  'low_24h': 17807.62,
  'price_change_24h': -2.5204812143165327,
  'price_change_percentage_24h': -0.36942,
  'market_cap_change_24h': -378851070098.84375,
  'market_cap_change_percentage_24h': -0.22165,
  'circulating_supply': 9575258938.40892,
  'total_supply': 9576464149.406918,
  'max_supply': None,
  'ath': 18315.99,
  'ath_change_percentage': -2.75634,
  'ath_date': '2026-07-15T22:30:40.000Z',
  'atl': 14517.43,
  'atl_change_percentage': 22.68794,
  'atl_date': '2024-10-02T11:53:21.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 238.98,
  'market_cap': 169505497715248,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 273031142925436,
  'total_volume': 429638443207,
  'high_24h': 252.53,
  'low_24h': 238.42,
  'price_change_24h': -12.249486336024518,
  'price_change_percentage_24h': -5.26503,
  'market_cap_change_24h': -8678626723694.3125,
  'market_cap_change_percentage_24h': -4.87059,
  'circulating_supply': 709239700254.0453,
  'total_supply': 1142408526965.963,
  'max_supply': 1150000000000.0,
  'ath': 344.1,
  'ath_change_percentage': -30.54858,
  'ath_date': '2026-08-25T19:53:00.000Z',
  'atl': 36.45,
  'atl_change_percentage': 555.71517,
  'atl_date': '2025-09-14T00:56:57.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 4418.39,
  'market_cap': 165831177446411,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 198843312080864,
  'total_volume': 14862610289229,
  'high_24h': 4521.1,
  'low_24h': 4282.4,
  'price_change_24h': 55.11,
  'price_change_percentage_24h': 0.88629,
  'market_cap_change_24h': 2108256119418,
  'market_cap_change_percentage_24h': 1.2877,
  'circulating_supply': 37529061988.535576,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 44039,
  'ath_change_percentage': -89.96713,
  'ath_date': '2021-09-01T22:00:10.000Z',
  'atl': 284.96,
  'atl_change_percentage': 1450.50831,
  'atl_date': '2020-03-12T18:22:55.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 159674,
  'market_cap': 146877481460863,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 157317238401963,
  'total_volume': 2606410439,
  'high_24h': 160394,
  'low_24h': 158049,
  'price_change_24h': 1291.55,
  'price_change_percentage_24h': 0.46215,
  'market_cap_change_24h': 1187955627632,
  'market_cap_change_percentage_24h': 0.8154,
  'circulating_supply': 919857851.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 184516,
  'ath_change_percentage': -13.46307,
  'ath_date': '2026-05-04T09:35:00.000Z',
  'atl': 11148.85,
  'atl_change_percentage': 1332.20335,
  'atl_date': '2019-12-31T04:15:15.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 3773.34,
  'market_cap': 131810425498580,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 188674559525674,
  'total_volume': 7847999615922,
  'high_24h': 3914.5,
  'low_24h': 3673.57,
  'price_change_24h': 26.18,
  'price_change_percentage_24h': 0.35961,
  'market_cap_change_24h': 1100762828126,
  'market_cap_change_percentage_24h': 0.84214,
  'circulating_supply': 34931878551.08532,
  'total_supply': 50001786839.70148,
  'max_supply': None,
  'ath': 11808.12,
  'ath_change_percentage': -68.04449,
  'ath_date': '2018-01-02T16:00:00.000Z',
  'atl': 6.19,
  'atl_change_percentage': 60811.22169,
  'atl_date': '2015-03-04T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 5741129,
  'market_cap': 115306999279602,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 115306999279602,
  'total_volume': 15828385050657,
  'high_24h': 5853163,
  'low_24h': 4663319,
  'price_change_24h': 1024412,
  'price_change_percentage_24h': 21.28653,
  'market_cap_change_24h': 20538016517317,
  'market_cap_change_percentage_24h': 21.67167,
  'circulating_supply': 20092765.52165077,
  'total_supply': 20092803.02165077,
  'max_supply': 21000000.0,
  'ath': 51400851,
  'ath_change_percentage': -88.83067,
  'ath_date': '2017-12-19T16:00:00.000Z',
  'atl': 1121286,
  'atl_change_percentage': 412.01283,
  'atl_date': '2018-12-15T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'near',
  'symbol': 'near',
  'name': 'NEAR Protocol',
  'image': 'https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367',
  'current_price': 79160,
  'market_cap': 103392633222429,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 103392635041887,
  'total_volume': 32731133579742,
  'high_24h': 82837,
  'low_24h': 69812,
  'price_change_24h': 6402.52,
  'price_change_percentage_24h': 8.52713,
  'market_cap_change_24h': 8304264957763,
  'market_cap_change_percentage_24h': 8.73321,
  'circulating_supply': 1306999708.0,
  'total_supply': 1306999679.0,
  'max_supply': None,
  'ath': 292609,
  'ath_change_percentage': -72.94676,
  'ath_date': '2022-01-16T14:09:45.000Z',
  'atl': 7636.89,
  'atl_change_percentage': 936.54966,
  'atl_date': '2020-11-04T07:44:20.000Z',
  'roi': None,
  'last_updated': '2026-09-22T16:19:10.000Z'},
 {'id': 'uniswap',

In [8]:
import requests

url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    "vs_currency": "idr",
    "per_page": 5
}

response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    for coin in data:
        print(f"Nama Kripto : {coin['name']}")
        print(f"Harga IDR   : Rp {coin['current_price']:,}")
        print("-" * 30)
else:
    print("Gagal ngambil data")

Nama Kripto : Bitcoin
Harga IDR   : Rp 1,538,152,424
------------------------------
Nama Kripto : Ethereum
Harga IDR   : Rp 48,799,098
------------------------------
Nama Kripto : Tether
Harga IDR   : Rp 17,817.71
------------------------------
Nama Kripto : BNB
Harga IDR   : Rp 14,034,387
------------------------------
Nama Kripto : XRP
Harga IDR   : Rp 27,897
------------------------------